/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Tripbite api
 * OpenAPI spec version: v1.0.0
 */
import type { AvatarResponseDto } from './avatarResponseDto';

export interface ApiResponseAvatarResponseDto {
  success?: boolean;
  /** @nullable */
  message?: string | null;
  data?: AvatarResponseDto | null;
}
