/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Tripbite api
 * OpenAPI spec version: v1.0.0
 */
import type { VapidPublicKeyDto } from './vapidPublicKeyDto';

export interface ApiResponseVapidPublicKeyDto {
  success?: boolean;
  /** @nullable */
  message?: string | null;
  data?: VapidPublicKeyDto | null;
}
