/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { DestinationPageDto } from './destinationPageDto';

export interface ApiResponseDestinationPageDto {
  success?: boolean;
  /** @nullable */
  message?: string | null;
  data?: DestinationPageDto | null;
}
