/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { StampsDto } from './stampsDto';

export interface ApiResponseStampsDto {
  success?: boolean;
  /** @nullable */
  message?: string | null;
  data?: StampsDto | null;
}
