/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Tripbite api
 * OpenAPI spec version: v1.0.0
 */
import type { WeeklyTopDestinationsDto } from './weeklyTopDestinationsDto';

export interface ApiResponseWeeklyTopDestinationsDto {
  success?: boolean;
  /** @nullable */
  message?: string | null;
  data?: WeeklyTopDestinationsDto | null;
}
