/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Tripbite api
 * OpenAPI spec version: v1.0.0
 */
import type { LoginResponseDto } from './loginResponseDto';

export interface ApiResponseLoginResponseDto {
  success?: boolean;
  /** @nullable */
  message?: string | null;
  data?: LoginResponseDto | null;
}
