/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { SavedTournamentDto } from './savedTournamentDto';

export interface ApiResponseListSavedTournamentDto {
  success?: boolean;
  /** @nullable */
  message?: string | null;
  /** @nullable */
  data?: SavedTournamentDto[] | null;
}
