/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { LoginResponseDto } from './loginResponseDto';

export interface ApiResponseLoginResponseDto {
  success?: boolean;
  /** @nullable */
  message?: string | null;
  data?: LoginResponseDto | null;
}
