/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Tripbite api
 * OpenAPI spec version: v1.0.0
 */
import type { QuizDto } from './quizDto';

export interface ApiResponseQuizDto {
  success?: boolean;
  /** @nullable */
  message?: string | null;
  data?: QuizDto | null;
}
