/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { LetterPageDto } from './letterPageDto';

export interface ApiResponseLetterPageDto {
  success?: boolean;
  /** @nullable */
  message?: string | null;
  data?: LetterPageDto | null;
}
