/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Tripbite api
 * OpenAPI spec version: v1.0.0
 */
import type { RegionWinCountDto } from './regionWinCountDto';

export interface ApiResponseListRegionWinCountDto {
  success?: boolean;
  /** @nullable */
  message?: string | null;
  /** @nullable */
  data?: RegionWinCountDto[] | null;
}
