/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { UserResponseDto } from './userResponseDto';

export interface ApiResponseUserResponseDto {
  success?: boolean;
  /** @nullable */
  message?: string | null;
  data?: UserResponseDto | null;
}
