/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { QuizDto } from './quizDto';

export interface ApiResponseQuizDto {
  success?: boolean;
  /** @nullable */
  message?: string | null;
  data?: QuizDto | null;
}
