/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Tripbite api
 * OpenAPI spec version: v1.0.0
 */
import type { FindIdResponseDto } from './findIdResponseDto';

export interface ApiResponseFindIdResponseDto {
  success?: boolean;
  /** @nullable */
  message?: string | null;
  data?: FindIdResponseDto | null;
}
