/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Tripbite api
 * OpenAPI spec version: v1.0.0
 */
import type { UnreadCountDto } from './unreadCountDto';

export interface ApiResponseUnreadCountDto {
  success?: boolean;
  /** @nullable */
  message?: string | null;
  data?: UnreadCountDto | null;
}
