/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Tripbite api
 * OpenAPI spec version: v1.0.0
 */
import type { AppNotificationDtoType } from './appNotificationDtoType';

export interface AppNotificationDto {
  id?: number;
  type?: AppNotificationDtoType;
  title?: string;
  /** @nullable */
  body?: string | null;
  /** @nullable */
  link?: string | null;
  read?: boolean;
  createdAt?: string;
}
