/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Tripbite api
 * OpenAPI spec version: v1.0.0
 */

export type AppNotificationDtoType = typeof AppNotificationDtoType[keyof typeof AppNotificationDtoType];


export const AppNotificationDtoType = {
  letterreceived: 'letter.received',
  letterliked: 'letter.liked',
  letterdelivered: 'letter.delivered',
  tournamentshared: 'tournament.shared',
  event: 'event',
  security: 'security',
} as const;
