/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Tripbite api
 * OpenAPI spec version: v1.0.0
 */

export interface AvatarResponseDto {
  /** @nullable */
  avatarUrl?: string | null;
}
