/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Tripbite api
 * OpenAPI spec version: v1.0.0
 */
import type { LetterLocationRequestDto } from './letterLocationRequestDto';

export interface ComposeLetterRequestDto {
  /**
     * @minLength 5
     * @maxLength 5
     */
  body?: string;
  location?: LetterLocationRequestDto;
  anonymous?: boolean;
}
