/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Tripbite api
 * OpenAPI spec version: v1.0.0
 */
import type { DestinationDetailDtoCategory } from './destinationDetailDtoCategory';
import type { DestinationDetailDtoRegion } from './destinationDetailDtoRegion';

export interface DestinationDetailDto {
  id?: number;
  name?: string;
  category?: DestinationDetailDtoCategory;
  /** @nullable */
  region?: DestinationDetailDtoRegion;
  /** @nullable */
  imageUrl?: string | null;
  images?: string[];
  address?: string;
  /** @nullable */
  type?: string | null;
  /** @nullable */
  admissionFee?: string | null;
  /** @nullable */
  description?: string | null;
  tags?: string[];
  /** @nullable */
  eventStart?: string | null;
  /** @nullable */
  eventEnd?: string | null;
}
