/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type DestinationDetailDtoCategory = typeof DestinationDetailDtoCategory[keyof typeof DestinationDetailDtoCategory];


export const DestinationDetailDtoCategory = {
  attraction: 'attraction',
  festival: 'festival',
  experience: 'experience',
} as const;
