/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * @nullable
 */
export type DestinationDetailDtoRegion =
  | (typeof DestinationDetailDtoRegion)[keyof typeof DestinationDetailDtoRegion]
  | null;

export const DestinationDetailDtoRegion = {
  cheongju: 'cheongju',
  chungju: 'chungju',
  jecheon: 'jecheon',
  boeun: 'boeun',
  okcheon: 'okcheon',
  yeongdong: 'yeongdong',
  jincheon: 'jincheon',
  goesan: 'goesan',
  eumseong: 'eumseong',
  danyang: 'danyang',
  jeungpyeong: 'jeungpyeong',
} as const;
