/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Tripbite api
 * OpenAPI spec version: v1.0.0
 */
import type { DestinationDto } from './destinationDto';

export interface DestinationPageDto {
  items?: DestinationDto[];
  totalCount?: number;
  pageNo?: number;
  numOfRows?: number;
}
