/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Tripbite api
 * OpenAPI spec version: v1.0.0
 */

export type DestinationDtoCategory = typeof DestinationDtoCategory[keyof typeof DestinationDtoCategory];


export const DestinationDtoCategory = {
  attraction: 'attraction',
  festival: 'festival',
  experience: 'experience',
} as const;
