/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Tripbite api
 * OpenAPI spec version: v1.0.0
 */
import type { DestinationDtoCategory } from './destinationDtoCategory';
import type { DestinationDtoRegion } from './destinationDtoRegion';

export interface DestinationDto {
  id?: number;
  name?: string;
  category?: DestinationDtoCategory;
  /** @nullable */
  region?: DestinationDtoRegion;
  address?: string;
  /** @nullable */
  imageUrl?: string | null;
}
