/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type GetList1Region =
  (typeof GetList1Region)[keyof typeof GetList1Region];

export const GetList1Region = {
  cheongju: 'cheongju',
  chungju: 'chungju',
  jecheon: 'jecheon',
  boeun: 'boeun',
  okcheon: 'okcheon',
  yeongdong: 'yeongdong',
  jincheon: 'jincheon',
  goesan: 'goesan',
  eumseong: 'eumseong',
  danyang: 'danyang',
  jeungpyeong: 'jeungpyeong',
} as const;
