/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Tripbite api
 * OpenAPI spec version: v1.0.0
 */

export type GetList2Category = typeof GetList2Category[keyof typeof GetList2Category];


export const GetList2Category = {
  attraction: 'attraction',
  festival: 'festival',
  experience: 'experience',
} as const;
