/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type GetList1Category =
  (typeof GetList1Category)[keyof typeof GetList1Category];

export const GetList1Category = {
  attraction: 'attraction',
  festival: 'festival',
  experience: 'experience',
} as const;
