/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { GetList1Category } from './getList1Category';
import type { GetList1Region } from './getList1Region';

export type GetList1Params = {
  category: GetList1Category;
  region?: GetList1Region;
  pageNo?: number;
  numOfRows?: number;
};
