/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Tripbite api
 * OpenAPI spec version: v1.0.0
 */
import type { GetList2Category } from './getList2Category';
import type { GetList2Region } from './getList2Region';

export type GetList2Params = {
category: GetList2Category;
region?: GetList2Region;
pageNo?: number;
numOfRows?: number;
};
