/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Tripbite api
 * OpenAPI spec version: v1.0.0
 */

export type GetRandomCategory = typeof GetRandomCategory[keyof typeof GetRandomCategory];


export const GetRandomCategory = {
  attraction: 'attraction',
  festival: 'festival',
  experience: 'experience',
} as const;
