/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type GetRandomCategory =
  (typeof GetRandomCategory)[keyof typeof GetRandomCategory];

export const GetRandomCategory = {
  attraction: 'attraction',
  festival: 'festival',
  experience: 'experience',
} as const;
