/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Tripbite api
 * OpenAPI spec version: v1.0.0
 */

export type GetRandomSeason = typeof GetRandomSeason[keyof typeof GetRandomSeason];


export const GetRandomSeason = {
  spring: 'spring',
  summer: 'summer',
  autumn: 'autumn',
  winter: 'winter',
} as const;
