/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { GetRandomCategory } from './getRandomCategory';
import type { GetRandomRegion } from './getRandomRegion';
import type { GetRandomSeason } from './getRandomSeason';

export type GetRandomParams = {
region?: GetRandomRegion;
season?: GetRandomSeason;
category?: GetRandomCategory;
size?: number;
};
