/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type GetWeeklyTopDestinationsParams = {
year?: number;
month?: number;
weekOfMonth?: number;
size?: number;
};
