/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Tripbite api
 * OpenAPI spec version: v1.0.0
 */

export type GetWeeklyTopDestinationsParams = {
year?: number;
month?: number;
weekOfMonth?: number;
size?: number;
};
