/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { LetterDto } from './letterDto';

export interface LetterPageDto {
  items?: LetterDto[];
  /** @nullable */
  nextCursor?: number | null;
}
