/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Tripbite api
 * OpenAPI spec version: v1.0.0
 */
import type { LetterLocationRequestDtoRegionCode } from './letterLocationRequestDtoRegionCode';

export interface LetterLocationRequestDto {
  regionCode?: LetterLocationRequestDtoRegionCode;
  /**
     * @minLength 1
     * @maxLength 100
     */
  label?: string;
}
