/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Tripbite api
 * OpenAPI spec version: v1.0.0
 */

export interface LoginRequestDto {
  /** @minLength 1 */
  username: string;
  /** @minLength 1 */
  password: string;
}
