/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface LoginRequestDto {
  /** @minLength 1 */
  username: string;
  /** @minLength 1 */
  password: string;
}
