/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Tripbite api
 * OpenAPI spec version: v1.0.0
 */
import type { AppNotificationDto } from './appNotificationDto';

export interface NotificationListDto {
  items?: AppNotificationDto[];
  unreadCount?: number;
  /** @nullable */
  nextCursor?: number | null;
}
