/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { OngoingFestivalItemDto } from './ongoingFestivalItemDto';
import type { OngoingFestivalsDtoType } from './ongoingFestivalsDtoType';

export interface OngoingFestivalsDto {
  type?: OngoingFestivalsDtoType;
  items?: OngoingFestivalItemDto[];
}
