/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Tripbite api
 * OpenAPI spec version: v1.0.0
 */

export type OngoingFestivalsDtoType = typeof OngoingFestivalsDtoType[keyof typeof OngoingFestivalsDtoType];


export const OngoingFestivalsDtoType = {
  ongoing: 'ongoing',
  upcoming: 'upcoming',
  popular: 'popular',
} as const;
