/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface OngoingFestivalItemDto {
  id?: number;
  name?: string;
  /** @nullable */
  imageUrl?: string | null;
  /** @nullable */
  regionLabel?: string | null;
  /** @nullable */
  daysToStart?: number | null;
  /** @nullable */
  eventStartDate?: string | null;
  /** @nullable */
  eventEndDate?: string | null;
}
