/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type OngoingFestivalsDtoType =
  (typeof OngoingFestivalsDtoType)[keyof typeof OngoingFestivalsDtoType];

export const OngoingFestivalsDtoType = {
  ongoing: 'ongoing',
  upcoming: 'upcoming',
  popular: 'popular',
} as const;
