/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Tripbite api
 * OpenAPI spec version: v1.0.0
 */

export interface PushSubscriptionDto {
  id?: number;
  /** @nullable */
  userAgent?: string | null;
  createdAt?: string;
}
