/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface QuizAnswerDto {
  /**
     * @minimum 1
     * @maximum 5
     */
  questionId?: number;
  /**
     * @minimum 1
     * @maximum 4
     */
  optionId?: number;
}
