/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Tripbite api
 * OpenAPI spec version: v1.0.0
 */
import type { QuizQuestionDto } from './quizQuestionDto';

export interface QuizDto {
  questions?: QuizQuestionDto[];
}
