/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { QuizQuestionDto } from './quizQuestionDto';

export interface QuizDto {
  questions?: QuizQuestionDto[];
}
