/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Tripbite api
 * OpenAPI spec version: v1.0.0
 */
import type { QuizOptionDto } from './quizOptionDto';

export interface QuizQuestionDto {
  id?: number;
  text?: string;
  options?: QuizOptionDto[];
}
