/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { RecordTournamentRequestDtoCategory } from './recordTournamentRequestDtoCategory';
import type { RecordTournamentRequestDtoRegion } from './recordTournamentRequestDtoRegion';

export interface RecordTournamentRequestDto {
  winnerId?: number;
  /** @minLength 1 */
  winnerName: string;
  region?: RecordTournamentRequestDtoRegion;
  category?: RecordTournamentRequestDtoCategory;
  tournamentSize?: number;
}
