/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Tripbite api
 * OpenAPI spec version: v1.0.0
 */

export type RecordTournamentRequestDtoCategory = typeof RecordTournamentRequestDtoCategory[keyof typeof RecordTournamentRequestDtoCategory];


export const RecordTournamentRequestDtoCategory = {
  attraction: 'attraction',
  festival: 'festival',
  experience: 'experience',
} as const;
