/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { RegionWinCountDtoRegion } from './regionWinCountDtoRegion';

export interface RegionWinCountDto {
  region?: RegionWinCountDtoRegion;
  winCount?: number;
}
