/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Tripbite api
 * OpenAPI spec version: v1.0.0
 */
import type { RegionWinCountDtoRegion } from './regionWinCountDtoRegion';

export interface RegionWinCountDto {
  region?: RegionWinCountDtoRegion;
  winCount?: number;
}
