/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Tripbite api
 * OpenAPI spec version: v1.0.0
 */

export interface ResetPasswordRequestDto {
  /** @minLength 1 */
  token: string;
  /**
     * @minLength 10
     * @maxLength 2147483647
     */
  password?: string;
}
