/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Tripbite api
 * OpenAPI spec version: v1.0.0
 */
import type { DestinationDto } from './destinationDto';

export interface SavedTournamentDto {
  id?: number;
  destination?: DestinationDto;
  savedAt?: string;
}
