/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { DestinationDto } from './destinationDto';

export interface SavedTournamentDto {
  id?: number;
  destination?: DestinationDto;
  savedAt?: string;
}
