/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Tripbite api
 * OpenAPI spec version: v1.0.0
 */

export interface SignupRequestDto {
  /** @pattern ^[a-zA-Z0-9]{4,20}$ */
  username?: string;
  /**
     * @minLength 10
     * @maxLength 2147483647
     */
  password?: string;
  /** @minLength 1 */
  name: string;
  birthDate: string;
  email?: string;
  /** @pattern ^01[0-9]-?[0-9]{3,4}-?[0-9]{4}$ */
  phone?: string;
  /**
     * @minLength 2
     * @maxLength 23
     */
  nickname?: string;
}
