/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Tripbite api
 * OpenAPI spec version: v1.0.0
 */
import type { StampsDtoVisitedItem } from './stampsDtoVisitedItem';

export interface StampsDto {
  visited?: StampsDtoVisitedItem[];
  total?: number;
}
