/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { StampsDtoVisitedItem } from './stampsDtoVisitedItem';

export interface StampsDto {
  visited?: StampsDtoVisitedItem[];
  total?: number;
}
