/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Tripbite api
 * OpenAPI spec version: v1.0.0
 */
import type { QuizAnswerDto } from './quizAnswerDto';

export interface SubmitQuizDto {
  /**
     * @minItems 5
     * @maxItems 5
     */
  answers?: QuizAnswerDto[];
}
