/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { QuizAnswerDto } from './quizAnswerDto';

export interface SubmitQuizDto {
  /**
   * @minItems 5
   * @maxItems 5
   */
  answers?: QuizAnswerDto[];
}
