/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Tripbite api
 * OpenAPI spec version: v1.0.0
 */

export interface SubscribeKeysRequestDto {
  /** @minLength 1 */
  p256dh: string;
  /** @minLength 1 */
  auth: string;
}
