/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Tripbite api
 * OpenAPI spec version: v1.0.0
 */
import type { SubscribeKeysRequestDto } from './subscribeKeysRequestDto';

export interface SubscribeRequestDto {
  /** @minLength 1 */
  endpoint: string;
  keys?: SubscribeKeysRequestDto;
}
