/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { TournamentSummaryDtoCategory } from './tournamentSummaryDtoCategory';

export interface TournamentSummaryDto {
  id?: number;
  winnerName?: string;
  tournamentSize?: number;
  category?: TournamentSummaryDtoCategory;
  completedAt?: string;
}
