/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Tripbite api
 * OpenAPI spec version: v1.0.0
 */
import type { TravelTypeResultDtoCode } from './travelTypeResultDtoCode';

export interface TravelTypeResultDto {
  code?: TravelTypeResultDtoCode;
  title?: string;
  emoji?: string;
  description?: string;
  tags?: string[];
}
