/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type TravelTypeResultDtoCode =
  (typeof TravelTypeResultDtoCode)[keyof typeof TravelTypeResultDtoCode];

export const TravelTypeResultDtoCode = {
  adventurer: 'adventurer',
  explorer: 'explorer',
  relaxer: 'relaxer',
  foodie: 'foodie',
} as const;
