/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Tripbite api
 * OpenAPI spec version: v1.0.0
 */

export type TravelTypeResultDtoCode = typeof TravelTypeResultDtoCode[keyof typeof TravelTypeResultDtoCode];


export const TravelTypeResultDtoCode = {
  adventurer: 'adventurer',
  explorer: 'explorer',
  relaxer: 'relaxer',
  foodie: 'foodie',
} as const;
