/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Tripbite api
 * OpenAPI spec version: v1.0.0
 */

/**
 * @nullable
 */
export type UpdateMeRequestDtoTravelType = typeof UpdateMeRequestDtoTravelType[keyof typeof UpdateMeRequestDtoTravelType] | null;


export const UpdateMeRequestDtoTravelType = {
  adventurer: 'adventurer',
  explorer: 'explorer',
  relaxer: 'relaxer',
  foodie: 'foodie',
} as const;
