/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Tripbite api
 * OpenAPI spec version: v1.0.0
 */

export interface UpdateNotificationSettingsDto {
  /** @nullable */
  pushEnabled?: boolean | null;
  /** @nullable */
  inAppEnabled?: boolean | null;
  /** @nullable */
  letterReceived?: boolean | null;
  /** @nullable */
  letterLiked?: boolean | null;
}
