/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * @nullable
 */
export type UserResponseDtoTravelType =
  | (typeof UserResponseDtoTravelType)[keyof typeof UserResponseDtoTravelType]
  | null;

export const UserResponseDtoTravelType = {
  adventurer: 'adventurer',
  explorer: 'explorer',
  relaxer: 'relaxer',
  foodie: 'foodie',
} as const;
