/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { UserResponseDtoTravelType } from './userResponseDtoTravelType';

export interface UserResponseDto {
  id?: number;
  username?: string;
  name?: string;
  nickname?: string;
  email?: string;
  phone?: string;
  birthDate?: string;
  /** @nullable */
  travelType?: UserResponseDtoTravelType;
  createdAt?: string;
}
