/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Tripbite api
 * OpenAPI spec version: v1.0.0
 */
import type { WeeklyDestinationWinDto } from './weeklyDestinationWinDto';

export interface WeeklyTopDestinationsDto {
  year?: number;
  month?: number;
  weekOfMonth?: number;
  weekStart?: string;
  weekEnd?: string;
  items?: WeeklyDestinationWinDto[];
}
