/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface WeeklyDestinationWinDto {
  destinationId?: number;
  destinationName?: string;
  winCount?: number;
}
