/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import { useInfiniteQuery, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type { ApiResponseOngoingFestivalsDto } from '../schemas';

import { orvalMutator } from '../../../services/api/orval-mutator';

/**
 * 오늘(서버 KST 기준) 날짜로 충북 축제를 조회해 아래 우선순위로 반환한다.
 *
 * 1. **ongoing** — 오늘 진행중인 축제가 있으면 그 목록.
 * 2. **upcoming** — 진행중인 축제가 없으면, 앞으로 예정된 축제를 임박한 순으로 반환. 이때만 daysToStart(오늘부터 시작일까지 남은 일수)가 채워진다.
 * 3. **popular** — 진행중/예정 축제가 둘 다 없으면(지자체가 아직 그 해 축제 일정을 TourAPI에 등록하지 않은 시기에 실제로 발생할 수 있음), 조회순(인기 근사치) 축제 목록으로 대체한다. 이 목록은 일정 정보가 없어 eventStartDate/eventEndDate/daysToStart가 항상 null이다.
 *
 * 응답의 type 필드로 위 세 단계 중 어느 것이 내려왔는지 구분한다.
 *
 * **실호출로 확인한 현재 상태(2026-07 기준)**: 충북(areaCode=33)은 2026년 축제 일정이 TourAPI에 아직 하나도 등록되어 있지 않다 — 전국 단위로는 2026년 데이터가 있는 걸 확인했지만 충북만 비어 있음. 따라서 현재는 이 API를 호출하면 항상 type=popular로 응답한다(ongoing/upcoming은 지자체가 2026년 축제를 등록해야 실제로 나타남).
 * @summary 지금 열리고 있는 축제 조회 (3단계 폴백)
 */
export const getOngoingFestivals = (signal?: AbortSignal) => {
  return orvalMutator<ApiResponseOngoingFestivalsDto>({
    url: `/regions/ongoing-festivals`,
    method: 'GET',
    signal,
  });
};

export const getGetOngoingFestivalsInfiniteQueryKey = () => {
  return ['infinite', `/regions/ongoing-festivals`] as const;
};

export const getGetOngoingFestivalsQueryKey = () => {
  return [`/regions/ongoing-festivals`] as const;
};

export const getGetOngoingFestivalsInfiniteQueryOptions = <
  TData = InfiniteData<Awaited<ReturnType<typeof getOngoingFestivals>>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseInfiniteQueryOptions<
      Awaited<ReturnType<typeof getOngoingFestivals>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetOngoingFestivalsInfiniteQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getOngoingFestivals>>
  > = ({ signal }) => getOngoingFestivals(signal);

  return { queryKey, queryFn, ...queryOptions } as UseInfiniteQueryOptions<
    Awaited<ReturnType<typeof getOngoingFestivals>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetOngoingFestivalsInfiniteQueryResult = NonNullable<
  Awaited<ReturnType<typeof getOngoingFestivals>>
>;
export type GetOngoingFestivalsInfiniteQueryError = unknown;

export function useGetOngoingFestivalsInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getOngoingFestivals>>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getOngoingFestivals>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOngoingFestivals>>,
          TError,
          Awaited<ReturnType<typeof getOngoingFestivals>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseInfiniteQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetOngoingFestivalsInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getOngoingFestivals>>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getOngoingFestivals>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOngoingFestivals>>,
          TError,
          Awaited<ReturnType<typeof getOngoingFestivals>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetOngoingFestivalsInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getOngoingFestivals>>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getOngoingFestivals>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 지금 열리고 있는 축제 조회 (3단계 폴백)
 */

export function useGetOngoingFestivalsInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getOngoingFestivals>>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getOngoingFestivals>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetOngoingFestivalsInfiniteQueryOptions(options);

  const query = useInfiniteQuery(
    queryOptions,
    queryClient,
  ) as UseInfiniteQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

export const getGetOngoingFestivalsQueryOptions = <
  TData = Awaited<ReturnType<typeof getOngoingFestivals>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getOngoingFestivals>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetOngoingFestivalsQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getOngoingFestivals>>
  > = ({ signal }) => getOngoingFestivals(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getOngoingFestivals>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetOngoingFestivalsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getOngoingFestivals>>
>;
export type GetOngoingFestivalsQueryError = unknown;

export function useGetOngoingFestivals<
  TData = Awaited<ReturnType<typeof getOngoingFestivals>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getOngoingFestivals>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOngoingFestivals>>,
          TError,
          Awaited<ReturnType<typeof getOngoingFestivals>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetOngoingFestivals<
  TData = Awaited<ReturnType<typeof getOngoingFestivals>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getOngoingFestivals>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOngoingFestivals>>,
          TError,
          Awaited<ReturnType<typeof getOngoingFestivals>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetOngoingFestivals<
  TData = Awaited<ReturnType<typeof getOngoingFestivals>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getOngoingFestivals>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 지금 열리고 있는 축제 조회 (3단계 폴백)
 */

export function useGetOngoingFestivals<
  TData = Awaited<ReturnType<typeof getOngoingFestivals>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getOngoingFestivals>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetOngoingFestivalsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
