/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Tripbite api
 * OpenAPI spec version: v1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ApiResponseFindIdResponseDto,
  ApiResponseLoginResponseDto,
  ApiResponseUnit,
  FindIdRequestDto,
  ForgotPasswordRequestDto,
  LoginRequestDto,
  ResetPasswordRequestDto,
  SignupRequestDto
} from '../schemas';

import { orvalMutator } from '../../../services/api/orval-mutator';




/**
 * 아이디/비밀번호/이름/생년월일/이메일/휴대폰/닉네임을 받아 계정을 생성한다.
 * @summary 회원가입
 */
export const signup = (
    signupRequestDto: SignupRequestDto,
 signal?: AbortSignal
) => {


      return orvalMutator<ApiResponseUnit>(
      {url: `/auth/signup`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: signupRequestDto, signal
    },
      );
    }




export const getSignupQueryKey = (signupRequestDto?: SignupRequestDto,) => {
    return [
    'POST', `/auth/signup`, signupRequestDto
    ] as const;
    }


export const getSignupQueryOptions = <TData = Awaited<ReturnType<typeof signup>>, TError = unknown>(signupRequestDto: SignupRequestDto, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof signup>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSignupQueryKey(signupRequestDto);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof signup>>> = ({ signal }) => signup(signupRequestDto, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof signup>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SignupQueryResult = NonNullable<Awaited<ReturnType<typeof signup>>>
export type SignupQueryError = unknown


export function useSignup<TData = Awaited<ReturnType<typeof signup>>, TError = unknown>(
 signupRequestDto: SignupRequestDto, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof signup>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof signup>>,
          TError,
          Awaited<ReturnType<typeof signup>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSignup<TData = Awaited<ReturnType<typeof signup>>, TError = unknown>(
 signupRequestDto: SignupRequestDto, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof signup>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof signup>>,
          TError,
          Awaited<ReturnType<typeof signup>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSignup<TData = Awaited<ReturnType<typeof signup>>, TError = unknown>(
 signupRequestDto: SignupRequestDto, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof signup>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 회원가입
 */

export function useSignup<TData = Awaited<ReturnType<typeof signup>>, TError = unknown>(
 signupRequestDto: SignupRequestDto, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof signup>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSignupQueryOptions(signupRequestDto,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * forgot-password로 발급된 토큰(30분 유효, 1회용)을 검증하고 새 비밀번호로 바꾼다. 실패 시 400 RESET_TOKEN_INVALID(없거나 이미 사용된 토큰) 또는 RESET_TOKEN_EXPIRED.
 * @summary 비밀번호 재설정
 */
export const resetPassword = (
    resetPasswordRequestDto: ResetPasswordRequestDto,
 signal?: AbortSignal
) => {


      return orvalMutator<ApiResponseUnit>(
      {url: `/auth/reset-password`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: resetPasswordRequestDto, signal
    },
      );
    }




export const getResetPasswordQueryKey = (resetPasswordRequestDto?: ResetPasswordRequestDto,) => {
    return [
    'POST', `/auth/reset-password`, resetPasswordRequestDto
    ] as const;
    }


export const getResetPasswordQueryOptions = <TData = Awaited<ReturnType<typeof resetPassword>>, TError = unknown>(resetPasswordRequestDto: ResetPasswordRequestDto, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof resetPassword>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getResetPasswordQueryKey(resetPasswordRequestDto);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof resetPassword>>> = ({ signal }) => resetPassword(resetPasswordRequestDto, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof resetPassword>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ResetPasswordQueryResult = NonNullable<Awaited<ReturnType<typeof resetPassword>>>
export type ResetPasswordQueryError = unknown


export function useResetPassword<TData = Awaited<ReturnType<typeof resetPassword>>, TError = unknown>(
 resetPasswordRequestDto: ResetPasswordRequestDto, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof resetPassword>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof resetPassword>>,
          TError,
          Awaited<ReturnType<typeof resetPassword>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useResetPassword<TData = Awaited<ReturnType<typeof resetPassword>>, TError = unknown>(
 resetPasswordRequestDto: ResetPasswordRequestDto, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof resetPassword>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof resetPassword>>,
          TError,
          Awaited<ReturnType<typeof resetPassword>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useResetPassword<TData = Awaited<ReturnType<typeof resetPassword>>, TError = unknown>(
 resetPasswordRequestDto: ResetPasswordRequestDto, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof resetPassword>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 비밀번호 재설정
 */

export function useResetPassword<TData = Awaited<ReturnType<typeof resetPassword>>, TError = unknown>(
 resetPasswordRequestDto: ResetPasswordRequestDto, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof resetPassword>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getResetPasswordQueryOptions(resetPasswordRequestDto,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * 현재 세션을 즉시 무효화한다. 이후 같은 JSESSIONID로 요청해도 인증에 실패한다.
 * @summary 로그아웃
 */
export const logout = (

 signal?: AbortSignal
) => {


      return orvalMutator<ApiResponseUnit>(
      {url: `/auth/logout`, method: 'POST', signal
    },
      );
    }




export const getLogoutQueryKey = () => {
    return [
    'POST', `/auth/logout`
    ] as const;
    }


export const getLogoutQueryOptions = <TData = Awaited<ReturnType<typeof logout>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof logout>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getLogoutQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof logout>>> = ({ signal }) => logout(signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof logout>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type LogoutQueryResult = NonNullable<Awaited<ReturnType<typeof logout>>>
export type LogoutQueryError = unknown


export function useLogout<TData = Awaited<ReturnType<typeof logout>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof logout>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof logout>>,
          TError,
          Awaited<ReturnType<typeof logout>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useLogout<TData = Awaited<ReturnType<typeof logout>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof logout>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof logout>>,
          TError,
          Awaited<ReturnType<typeof logout>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useLogout<TData = Awaited<ReturnType<typeof logout>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof logout>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 로그아웃
 */

export function useLogout<TData = Awaited<ReturnType<typeof logout>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof logout>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getLogoutQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * 아이디/비밀번호로 인증하고 세션을 생성한다. JSESSIONID 쿠키가 응답 헤더로 발급된다.
 * @summary 로그인
 */
export const login = (
    loginRequestDto: LoginRequestDto,
 signal?: AbortSignal
) => {


      return orvalMutator<ApiResponseLoginResponseDto>(
      {url: `/auth/login`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: loginRequestDto, signal
    },
      );
    }




export const getLoginQueryKey = (loginRequestDto?: LoginRequestDto,) => {
    return [
    'POST', `/auth/login`, loginRequestDto
    ] as const;
    }


export const getLoginQueryOptions = <TData = Awaited<ReturnType<typeof login>>, TError = unknown>(loginRequestDto: LoginRequestDto, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof login>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getLoginQueryKey(loginRequestDto);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof login>>> = ({ signal }) => login(loginRequestDto, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof login>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type LoginQueryResult = NonNullable<Awaited<ReturnType<typeof login>>>
export type LoginQueryError = unknown


export function useLogin<TData = Awaited<ReturnType<typeof login>>, TError = unknown>(
 loginRequestDto: LoginRequestDto, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof login>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof login>>,
          TError,
          Awaited<ReturnType<typeof login>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useLogin<TData = Awaited<ReturnType<typeof login>>, TError = unknown>(
 loginRequestDto: LoginRequestDto, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof login>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof login>>,
          TError,
          Awaited<ReturnType<typeof login>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useLogin<TData = Awaited<ReturnType<typeof login>>, TError = unknown>(
 loginRequestDto: LoginRequestDto, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof login>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 로그인
 */

export function useLogin<TData = Awaited<ReturnType<typeof login>>, TError = unknown>(
 loginRequestDto: LoginRequestDto, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof login>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getLoginQueryOptions(loginRequestDto,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * username과 email이 모두 일치하는 계정에만 재설정 링크를 발송한다. 일치 여부와 무관하게 항상 200 + success:true로 응답한다(계정 존재 유추 방지).
 * @summary 비밀번호 재설정 메일 발송
 */
export const forgotPassword = (
    forgotPasswordRequestDto: ForgotPasswordRequestDto,
 signal?: AbortSignal
) => {


      return orvalMutator<ApiResponseUnit>(
      {url: `/auth/forgot-password`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: forgotPasswordRequestDto, signal
    },
      );
    }




export const getForgotPasswordQueryKey = (forgotPasswordRequestDto?: ForgotPasswordRequestDto,) => {
    return [
    'POST', `/auth/forgot-password`, forgotPasswordRequestDto
    ] as const;
    }


export const getForgotPasswordQueryOptions = <TData = Awaited<ReturnType<typeof forgotPassword>>, TError = unknown>(forgotPasswordRequestDto: ForgotPasswordRequestDto, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof forgotPassword>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getForgotPasswordQueryKey(forgotPasswordRequestDto);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof forgotPassword>>> = ({ signal }) => forgotPassword(forgotPasswordRequestDto, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof forgotPassword>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ForgotPasswordQueryResult = NonNullable<Awaited<ReturnType<typeof forgotPassword>>>
export type ForgotPasswordQueryError = unknown


export function useForgotPassword<TData = Awaited<ReturnType<typeof forgotPassword>>, TError = unknown>(
 forgotPasswordRequestDto: ForgotPasswordRequestDto, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof forgotPassword>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof forgotPassword>>,
          TError,
          Awaited<ReturnType<typeof forgotPassword>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useForgotPassword<TData = Awaited<ReturnType<typeof forgotPassword>>, TError = unknown>(
 forgotPasswordRequestDto: ForgotPasswordRequestDto, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof forgotPassword>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof forgotPassword>>,
          TError,
          Awaited<ReturnType<typeof forgotPassword>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useForgotPassword<TData = Awaited<ReturnType<typeof forgotPassword>>, TError = unknown>(
 forgotPasswordRequestDto: ForgotPasswordRequestDto, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof forgotPassword>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 비밀번호 재설정 메일 발송
 */

export function useForgotPassword<TData = Awaited<ReturnType<typeof forgotPassword>>, TError = unknown>(
 forgotPasswordRequestDto: ForgotPasswordRequestDto, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof forgotPassword>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getForgotPasswordQueryOptions(forgotPasswordRequestDto,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * email로 가입된 계정을 조회해 마스킹된 username(예: tes***01)을 반환한다. 가입 내역이 없어도 항상 200 + username:null로 응답한다(이메일 가입 여부 유추 방지).
 * @summary 아이디 찾기
 */
export const findId = (
    findIdRequestDto: FindIdRequestDto,
 signal?: AbortSignal
) => {


      return orvalMutator<ApiResponseFindIdResponseDto>(
      {url: `/auth/find-id`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: findIdRequestDto, signal
    },
      );
    }




export const getFindIdQueryKey = (findIdRequestDto?: FindIdRequestDto,) => {
    return [
    'POST', `/auth/find-id`, findIdRequestDto
    ] as const;
    }


export const getFindIdQueryOptions = <TData = Awaited<ReturnType<typeof findId>>, TError = unknown>(findIdRequestDto: FindIdRequestDto, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findId>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getFindIdQueryKey(findIdRequestDto);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof findId>>> = ({ signal }) => findId(findIdRequestDto, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof findId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type FindIdQueryResult = NonNullable<Awaited<ReturnType<typeof findId>>>
export type FindIdQueryError = unknown


export function useFindId<TData = Awaited<ReturnType<typeof findId>>, TError = unknown>(
 findIdRequestDto: FindIdRequestDto, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof findId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof findId>>,
          TError,
          Awaited<ReturnType<typeof findId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFindId<TData = Awaited<ReturnType<typeof findId>>, TError = unknown>(
 findIdRequestDto: FindIdRequestDto, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof findId>>,
          TError,
          Awaited<ReturnType<typeof findId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFindId<TData = Awaited<ReturnType<typeof findId>>, TError = unknown>(
 findIdRequestDto: FindIdRequestDto, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findId>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 아이디 찾기
 */

export function useFindId<TData = Awaited<ReturnType<typeof findId>>, TError = unknown>(
 findIdRequestDto: FindIdRequestDto, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findId>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getFindIdQueryOptions(findIdRequestDto,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






