/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import { useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  ApiResponseLoginResponseDto,
  ApiResponseUnit,
  LoginRequestDto,
  SignupRequestDto,
} from '../schemas';

import { orvalMutator } from '../../../services/api/orval-mutator';

/**
 * 아이디/비밀번호/이름/생년월일/이메일/휴대폰/닉네임을 받아 계정을 생성한다.
 * @summary 회원가입
 */
export const signup = (
  signupRequestDto: SignupRequestDto,
  signal?: AbortSignal,
) => {
  return orvalMutator<ApiResponseUnit>({
    url: `/auth/signup`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: signupRequestDto,
    signal,
  });
};

export const getSignupQueryKey = (signupRequestDto?: SignupRequestDto) => {
  return ['POST', `/auth/signup`, signupRequestDto] as const;
};

export const getSignupQueryOptions = <
  TData = Awaited<ReturnType<typeof signup>>,
  TError = unknown,
>(
  signupRequestDto: SignupRequestDto,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof signup>>, TError, TData>
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getSignupQueryKey(signupRequestDto);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof signup>>> = ({
    signal,
  }) => signup(signupRequestDto, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof signup>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type SignupQueryResult = NonNullable<Awaited<ReturnType<typeof signup>>>;
export type SignupQueryError = unknown;

export function useSignup<
  TData = Awaited<ReturnType<typeof signup>>,
  TError = unknown,
>(
  signupRequestDto: SignupRequestDto,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof signup>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof signup>>,
          TError,
          Awaited<ReturnType<typeof signup>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useSignup<
  TData = Awaited<ReturnType<typeof signup>>,
  TError = unknown,
>(
  signupRequestDto: SignupRequestDto,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof signup>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof signup>>,
          TError,
          Awaited<ReturnType<typeof signup>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useSignup<
  TData = Awaited<ReturnType<typeof signup>>,
  TError = unknown,
>(
  signupRequestDto: SignupRequestDto,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof signup>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 회원가입
 */

export function useSignup<
  TData = Awaited<ReturnType<typeof signup>>,
  TError = unknown,
>(
  signupRequestDto: SignupRequestDto,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof signup>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getSignupQueryOptions(signupRequestDto, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * 현재 세션을 즉시 무효화한다. 이후 같은 JSESSIONID로 요청해도 인증에 실패한다.
 * @summary 로그아웃
 */
export const logout = (signal?: AbortSignal) => {
  return orvalMutator<ApiResponseUnit>({
    url: `/auth/logout`,
    method: 'POST',
    signal,
  });
};

export const getLogoutQueryKey = () => {
  return ['POST', `/auth/logout`] as const;
};

export const getLogoutQueryOptions = <
  TData = Awaited<ReturnType<typeof logout>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof logout>>, TError, TData>
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getLogoutQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof logout>>> = ({
    signal,
  }) => logout(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof logout>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type LogoutQueryResult = NonNullable<Awaited<ReturnType<typeof logout>>>;
export type LogoutQueryError = unknown;

export function useLogout<
  TData = Awaited<ReturnType<typeof logout>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof logout>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof logout>>,
          TError,
          Awaited<ReturnType<typeof logout>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useLogout<
  TData = Awaited<ReturnType<typeof logout>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof logout>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof logout>>,
          TError,
          Awaited<ReturnType<typeof logout>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useLogout<
  TData = Awaited<ReturnType<typeof logout>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof logout>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 로그아웃
 */

export function useLogout<
  TData = Awaited<ReturnType<typeof logout>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof logout>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getLogoutQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * 아이디/비밀번호로 인증하고 세션을 생성한다. JSESSIONID 쿠키가 응답 헤더로 발급된다.
 * @summary 로그인
 */
export const login = (
  loginRequestDto: LoginRequestDto,
  signal?: AbortSignal,
) => {
  return orvalMutator<ApiResponseLoginResponseDto>({
    url: `/auth/login`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: loginRequestDto,
    signal,
  });
};

export const getLoginQueryKey = (loginRequestDto?: LoginRequestDto) => {
  return ['POST', `/auth/login`, loginRequestDto] as const;
};

export const getLoginQueryOptions = <
  TData = Awaited<ReturnType<typeof login>>,
  TError = unknown,
>(
  loginRequestDto: LoginRequestDto,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof login>>, TError, TData>
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getLoginQueryKey(loginRequestDto);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof login>>> = ({
    signal,
  }) => login(loginRequestDto, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof login>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type LoginQueryResult = NonNullable<Awaited<ReturnType<typeof login>>>;
export type LoginQueryError = unknown;

export function useLogin<
  TData = Awaited<ReturnType<typeof login>>,
  TError = unknown,
>(
  loginRequestDto: LoginRequestDto,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof login>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof login>>,
          TError,
          Awaited<ReturnType<typeof login>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useLogin<
  TData = Awaited<ReturnType<typeof login>>,
  TError = unknown,
>(
  loginRequestDto: LoginRequestDto,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof login>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof login>>,
          TError,
          Awaited<ReturnType<typeof login>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useLogin<
  TData = Awaited<ReturnType<typeof login>>,
  TError = unknown,
>(
  loginRequestDto: LoginRequestDto,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof login>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 로그인
 */

export function useLogin<
  TData = Awaited<ReturnType<typeof login>>,
  TError = unknown,
>(
  loginRequestDto: LoginRequestDto,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof login>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getLoginQueryOptions(loginRequestDto, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
