/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Tripbite api
 * OpenAPI spec version: v1.0.0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  ApiResponseUserResponseDto,
  UserResponseDto
} from '../schemas';


export const getGetMeResponseUserResponseDtoMock = (overrideResponse: Partial<UserResponseDto> = {}): UserResponseDto => ({...{id: faker.helpers.arrayElement([faker.number.int(), undefined]), username: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), name: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), nickname: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), email: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), phone: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), birthDate: faker.helpers.arrayElement([faker.date.past().toISOString().slice(0, 10), undefined]), travelType: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.helpers.arrayElement(['adventurer','explorer','relaxer','foodie'] as const), null]), undefined]), createdAt: faker.helpers.arrayElement([faker.date.past().toISOString().slice(0, 19) + 'Z', undefined])}, ...overrideResponse});

export const getGetMeResponseMock = (overrideResponse: Partial<Extract<ApiResponseUserResponseDto, object>> = {}): ApiResponseUserResponseDto => ({success: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]), message: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), undefined]), data: faker.helpers.arrayElement([faker.helpers.arrayElement([{...getGetMeResponseUserResponseDtoMock()},null,]), undefined]), ...overrideResponse})

export const getUpdateMeResponseUserResponseDtoMock = (overrideResponse: Partial<UserResponseDto> = {}): UserResponseDto => ({...{id: faker.helpers.arrayElement([faker.number.int(), undefined]), username: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), name: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), nickname: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), email: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), phone: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), birthDate: faker.helpers.arrayElement([faker.date.past().toISOString().slice(0, 10), undefined]), travelType: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.helpers.arrayElement(['adventurer','explorer','relaxer','foodie'] as const), null]), undefined]), createdAt: faker.helpers.arrayElement([faker.date.past().toISOString().slice(0, 19) + 'Z', undefined])}, ...overrideResponse});

export const getUpdateMeResponseMock = (overrideResponse: Partial<Extract<ApiResponseUserResponseDto, object>> = {}): ApiResponseUserResponseDto => ({success: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]), message: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), undefined]), data: faker.helpers.arrayElement([faker.helpers.arrayElement([{...getUpdateMeResponseUserResponseDtoMock()},null,]), undefined]), ...overrideResponse})


export const getGetMeMockHandler = (overrideResponse?: ApiResponseUserResponseDto | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<ApiResponseUserResponseDto> | ApiResponseUserResponseDto), options?: RequestHandlerOptions) => {
  return http.get('*/me', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetMeResponseMock(),
      { status: 200
      })
  }, options)
}

export const getUpdateMeMockHandler = (overrideResponse?: ApiResponseUserResponseDto | ((info: Parameters<Parameters<typeof http.patch>[1]>[0]) => Promise<ApiResponseUserResponseDto> | ApiResponseUserResponseDto), options?: RequestHandlerOptions) => {
  return http.patch('*/me', async (info: Parameters<Parameters<typeof http.patch>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getUpdateMeResponseMock(),
      { status: 200
      })
  }, options)
}
export const getMeMock = () => [
  getGetMeMockHandler(),
  getUpdateMeMockHandler()
]
