/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Tripbite api
 * OpenAPI spec version: v1.0.0
 */
import {
  useInfiniteQuery,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ApiResponseAvatarResponseDto,
  ApiResponseUnit,
  ApiResponseUserResponseDto,
  ChangePasswordRequestDto,
  UpdateMeRequestDto,
  UploadAvatarBody
} from '../schemas';

import { orvalMutator } from '../../../services/api/orval-mutator';




/**
 * currentPassword가 일치해야 newPassword로 바뀐다(400 CURRENT_PASSWORD_MISMATCH). PATCH /me와 달리 현재 비밀번호 확인을 거치는 전용 경로.
 * @summary 비밀번호 변경
 */
export const changePassword = (
    changePasswordRequestDto: ChangePasswordRequestDto,
 signal?: AbortSignal
) => {


      return orvalMutator<ApiResponseUnit>(
      {url: `/me/change-password`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: changePasswordRequestDto, signal
    },
      );
    }




export const getChangePasswordQueryKey = (changePasswordRequestDto?: ChangePasswordRequestDto,) => {
    return [
    'POST', `/me/change-password`, changePasswordRequestDto
    ] as const;
    }


export const getChangePasswordQueryOptions = <TData = Awaited<ReturnType<typeof changePassword>>, TError = unknown>(changePasswordRequestDto: ChangePasswordRequestDto, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof changePassword>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getChangePasswordQueryKey(changePasswordRequestDto);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof changePassword>>> = ({ signal }) => changePassword(changePasswordRequestDto, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof changePassword>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ChangePasswordQueryResult = NonNullable<Awaited<ReturnType<typeof changePassword>>>
export type ChangePasswordQueryError = unknown


export function useChangePassword<TData = Awaited<ReturnType<typeof changePassword>>, TError = unknown>(
 changePasswordRequestDto: ChangePasswordRequestDto, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof changePassword>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof changePassword>>,
          TError,
          Awaited<ReturnType<typeof changePassword>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useChangePassword<TData = Awaited<ReturnType<typeof changePassword>>, TError = unknown>(
 changePasswordRequestDto: ChangePasswordRequestDto, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof changePassword>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof changePassword>>,
          TError,
          Awaited<ReturnType<typeof changePassword>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useChangePassword<TData = Awaited<ReturnType<typeof changePassword>>, TError = unknown>(
 changePasswordRequestDto: ChangePasswordRequestDto, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof changePassword>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 비밀번호 변경
 */

export function useChangePassword<TData = Awaited<ReturnType<typeof changePassword>>, TError = unknown>(
 changePasswordRequestDto: ChangePasswordRequestDto, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof changePassword>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getChangePasswordQueryOptions(changePasswordRequestDto,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * image/* 타입, 최대 10MB. 이미 업로드된 이미지가 있으면 덮어쓴다. 실패 시 422 AVATAR_TYPE_UNSUPPORTED(이미지 아닌 형식) 또는 AVATAR_TOO_LARGE(10MB 초과).
 * @summary 프로필 이미지 업로드
 */
export const uploadAvatar = (
    uploadAvatarBody?: UploadAvatarBody,
 signal?: AbortSignal
) => {

      const formData = new FormData();
if(uploadAvatarBody?.file !== undefined) {
 formData.append(`file`, uploadAvatarBody.file);
 }

      return orvalMutator<ApiResponseAvatarResponseDto>(
      {url: `/me/avatar`, method: 'POST',
      headers: {'Content-Type': 'multipart/form-data', },
       data: formData, signal
    },
      );
    }




export const getUploadAvatarQueryKey = (uploadAvatarBody?: UploadAvatarBody,) => {
    return [
    'POST', `/me/avatar`, uploadAvatarBody
    ] as const;
    }


export const getUploadAvatarQueryOptions = <TData = Awaited<ReturnType<typeof uploadAvatar>>, TError = unknown>(uploadAvatarBody?: UploadAvatarBody, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof uploadAvatar>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getUploadAvatarQueryKey(uploadAvatarBody);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof uploadAvatar>>> = ({ signal }) => uploadAvatar(uploadAvatarBody, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof uploadAvatar>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type UploadAvatarQueryResult = NonNullable<Awaited<ReturnType<typeof uploadAvatar>>>
export type UploadAvatarQueryError = unknown


export function useUploadAvatar<TData = Awaited<ReturnType<typeof uploadAvatar>>, TError = unknown>(
 uploadAvatarBody: undefined |  UploadAvatarBody, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof uploadAvatar>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof uploadAvatar>>,
          TError,
          Awaited<ReturnType<typeof uploadAvatar>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUploadAvatar<TData = Awaited<ReturnType<typeof uploadAvatar>>, TError = unknown>(
 uploadAvatarBody?: UploadAvatarBody, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof uploadAvatar>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof uploadAvatar>>,
          TError,
          Awaited<ReturnType<typeof uploadAvatar>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUploadAvatar<TData = Awaited<ReturnType<typeof uploadAvatar>>, TError = unknown>(
 uploadAvatarBody?: UploadAvatarBody, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof uploadAvatar>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 프로필 이미지 업로드
 */

export function useUploadAvatar<TData = Awaited<ReturnType<typeof uploadAvatar>>, TError = unknown>(
 uploadAvatarBody?: UploadAvatarBody, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof uploadAvatar>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getUploadAvatarQueryOptions(uploadAvatarBody,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * 업로드된 이미지가 없어도 멱등하게 avatarUrl:null로 응답한다.
 * @summary 프로필 이미지 삭제
 */
export const deleteAvatar = (

 signal?: AbortSignal
) => {


      return orvalMutator<ApiResponseAvatarResponseDto>(
      {url: `/me/avatar`, method: 'DELETE', signal
    },
      );
    }




export const getDeleteAvatarQueryKey = () => {
    return [
    'DELETE', `/me/avatar`
    ] as const;
    }


export const getDeleteAvatarQueryOptions = <TData = Awaited<ReturnType<typeof deleteAvatar>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deleteAvatar>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDeleteAvatarQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof deleteAvatar>>> = ({ signal }) => deleteAvatar(signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof deleteAvatar>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type DeleteAvatarQueryResult = NonNullable<Awaited<ReturnType<typeof deleteAvatar>>>
export type DeleteAvatarQueryError = unknown


export function useDeleteAvatar<TData = Awaited<ReturnType<typeof deleteAvatar>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof deleteAvatar>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof deleteAvatar>>,
          TError,
          Awaited<ReturnType<typeof deleteAvatar>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDeleteAvatar<TData = Awaited<ReturnType<typeof deleteAvatar>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deleteAvatar>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof deleteAvatar>>,
          TError,
          Awaited<ReturnType<typeof deleteAvatar>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDeleteAvatar<TData = Awaited<ReturnType<typeof deleteAvatar>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deleteAvatar>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 프로필 이미지 삭제
 */

export function useDeleteAvatar<TData = Awaited<ReturnType<typeof deleteAvatar>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deleteAvatar>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getDeleteAvatarQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * 현재 로그인한 사용자의 프로필(이름/생년월일/이메일/휴대폰/닉네임/여행유형 등)을 조회한다.
 * @summary 내 프로필 조회
 */
export const getMe = (

 signal?: AbortSignal
) => {


      return orvalMutator<ApiResponseUserResponseDto>(
      {url: `/me`, method: 'GET', signal
    },
      );
    }




export const getGetMeInfiniteQueryKey = () => {
    return [
    'infinite', `/me`
    ] as const;
    }

export const getGetMeQueryKey = () => {
    return [
    `/me`
    ] as const;
    }


export const getGetMeInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getMe>>>, TError = unknown>( options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMeInfiniteQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMe>>> = ({ signal }) => getMe(signal);





   return  { queryKey, queryFn, ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMeInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getMe>>>
export type GetMeInfiniteQueryError = unknown


export function useGetMeInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getMe>>>, TError = unknown>(
  options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMe>>,
          TError,
          Awaited<ReturnType<typeof getMe>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMeInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getMe>>>, TError = unknown>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMe>>,
          TError,
          Awaited<ReturnType<typeof getMe>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMeInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getMe>>>, TError = unknown>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 내 프로필 조회
 */

export function useGetMeInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getMe>>>, TError = unknown>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMeInfiniteQueryOptions(options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getGetMeQueryOptions = <TData = Awaited<ReturnType<typeof getMe>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMeQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMe>>> = ({ signal }) => getMe(signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMeQueryResult = NonNullable<Awaited<ReturnType<typeof getMe>>>
export type GetMeQueryError = unknown


export function useGetMe<TData = Awaited<ReturnType<typeof getMe>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMe>>,
          TError,
          Awaited<ReturnType<typeof getMe>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMe<TData = Awaited<ReturnType<typeof getMe>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMe>>,
          TError,
          Awaited<ReturnType<typeof getMe>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMe<TData = Awaited<ReturnType<typeof getMe>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 내 프로필 조회
 */

export function useGetMe<TData = Awaited<ReturnType<typeof getMe>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMeQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * 소프트 삭제(deletedAt 기록) 후 현재 세션을 즉시 무효화한다. 탈퇴한 계정으로는 이후 로그인도 실패한다(INVALID_CREDENTIALS와 동일하게 응답).
 * @summary 회원 탈퇴
 */
export const deleteMe = (

 signal?: AbortSignal
) => {


      return orvalMutator<void>(
      {url: `/me`, method: 'DELETE', signal
    },
      );
    }




export const getDeleteMeQueryKey = () => {
    return [
    'DELETE', `/me`
    ] as const;
    }


export const getDeleteMeQueryOptions = <TData = Awaited<ReturnType<typeof deleteMe>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deleteMe>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDeleteMeQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof deleteMe>>> = ({ signal }) => deleteMe(signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof deleteMe>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type DeleteMeQueryResult = NonNullable<Awaited<ReturnType<typeof deleteMe>>>
export type DeleteMeQueryError = unknown


export function useDeleteMe<TData = Awaited<ReturnType<typeof deleteMe>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof deleteMe>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof deleteMe>>,
          TError,
          Awaited<ReturnType<typeof deleteMe>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDeleteMe<TData = Awaited<ReturnType<typeof deleteMe>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deleteMe>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof deleteMe>>,
          TError,
          Awaited<ReturnType<typeof deleteMe>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDeleteMe<TData = Awaited<ReturnType<typeof deleteMe>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deleteMe>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 회원 탈퇴
 */

export function useDeleteMe<TData = Awaited<ReturnType<typeof deleteMe>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deleteMe>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getDeleteMeQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * username(아이디)을 제외한 전 필드(비밀번호/이름/생년월일/이메일/휴대폰/닉네임/여행유형)를 부분 수정한다. 요청 필드값이 null이거나 아예 없으면 해당 필드는 수정하지 않는다.
 * @summary 내 프로필 수정
 */
export const updateMe = (
    updateMeRequestDto: UpdateMeRequestDto,
 signal?: AbortSignal
) => {


      return orvalMutator<ApiResponseUserResponseDto>(
      {url: `/me`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateMeRequestDto, signal
    },
      );
    }




export const getUpdateMeQueryKey = (updateMeRequestDto?: UpdateMeRequestDto,) => {
    return [
    'PATCH', `/me`, updateMeRequestDto
    ] as const;
    }


export const getUpdateMeQueryOptions = <TData = Awaited<ReturnType<typeof updateMe>>, TError = unknown>(updateMeRequestDto: UpdateMeRequestDto, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof updateMe>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getUpdateMeQueryKey(updateMeRequestDto);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof updateMe>>> = ({ signal }) => updateMe(updateMeRequestDto, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof updateMe>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type UpdateMeQueryResult = NonNullable<Awaited<ReturnType<typeof updateMe>>>
export type UpdateMeQueryError = unknown


export function useUpdateMe<TData = Awaited<ReturnType<typeof updateMe>>, TError = unknown>(
 updateMeRequestDto: UpdateMeRequestDto, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof updateMe>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof updateMe>>,
          TError,
          Awaited<ReturnType<typeof updateMe>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUpdateMe<TData = Awaited<ReturnType<typeof updateMe>>, TError = unknown>(
 updateMeRequestDto: UpdateMeRequestDto, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof updateMe>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof updateMe>>,
          TError,
          Awaited<ReturnType<typeof updateMe>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUpdateMe<TData = Awaited<ReturnType<typeof updateMe>>, TError = unknown>(
 updateMeRequestDto: UpdateMeRequestDto, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof updateMe>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 내 프로필 수정
 */

export function useUpdateMe<TData = Awaited<ReturnType<typeof updateMe>>, TError = unknown>(
 updateMeRequestDto: UpdateMeRequestDto, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof updateMe>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getUpdateMeQueryOptions(updateMeRequestDto,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






