/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Tripbite api
 * OpenAPI spec version: v1.0.0
 */
import {
  useInfiniteQuery,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ApiResponseListPushSubscriptionDto,
  ApiResponseNotificationListDto,
  ApiResponseUnreadCountDto,
  ApiResponseVapidPublicKeyDto,
  GetList1Params,
  SubscribeRequestDto,
  UnsubscribeRequestDto
} from '../schemas';

import { orvalMutator } from '../../../services/api/orval-mutator';




/**
 * 본인의 알림만 가능. 이미 읽은 알림이어도 멱등하게 204를 반환한다.
 * @summary 단건 읽음 처리
 */
export const read = (
    id: number,
 signal?: AbortSignal
) => {


      return orvalMutator<void>(
      {url: `/notifications/${id}/read`, method: 'POST', signal
    },
      );
    }




export const getReadQueryKey = (id: number,) => {
    return [
    'POST', `/notifications/${id}/read`
    ] as const;
    }


export const getReadQueryOptions = <TData = Awaited<ReturnType<typeof read>>, TError = unknown>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof read>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getReadQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof read>>> = ({ signal }) => read(id, signal);





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof read>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ReadQueryResult = NonNullable<Awaited<ReturnType<typeof read>>>
export type ReadQueryError = unknown


export function useRead<TData = Awaited<ReturnType<typeof read>>, TError = unknown>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof read>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof read>>,
          TError,
          Awaited<ReturnType<typeof read>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useRead<TData = Awaited<ReturnType<typeof read>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof read>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof read>>,
          TError,
          Awaited<ReturnType<typeof read>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useRead<TData = Awaited<ReturnType<typeof read>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof read>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 단건 읽음 처리
 */

export function useRead<TData = Awaited<ReturnType<typeof read>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof read>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getReadQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * 본인 소유 endpoint만 해제된다.
 * @summary 웹 푸시 구독 해제
 */
export const unsubscribe = (
    unsubscribeRequestDto: UnsubscribeRequestDto,
 signal?: AbortSignal
) => {


      return orvalMutator<void>(
      {url: `/notifications/unsubscribe`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: unsubscribeRequestDto, signal
    },
      );
    }




export const getUnsubscribeQueryKey = (unsubscribeRequestDto?: UnsubscribeRequestDto,) => {
    return [
    'POST', `/notifications/unsubscribe`, unsubscribeRequestDto
    ] as const;
    }


export const getUnsubscribeQueryOptions = <TData = Awaited<ReturnType<typeof unsubscribe>>, TError = unknown>(unsubscribeRequestDto: UnsubscribeRequestDto, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof unsubscribe>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getUnsubscribeQueryKey(unsubscribeRequestDto);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof unsubscribe>>> = ({ signal }) => unsubscribe(unsubscribeRequestDto, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof unsubscribe>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type UnsubscribeQueryResult = NonNullable<Awaited<ReturnType<typeof unsubscribe>>>
export type UnsubscribeQueryError = unknown


export function useUnsubscribe<TData = Awaited<ReturnType<typeof unsubscribe>>, TError = unknown>(
 unsubscribeRequestDto: UnsubscribeRequestDto, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof unsubscribe>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof unsubscribe>>,
          TError,
          Awaited<ReturnType<typeof unsubscribe>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUnsubscribe<TData = Awaited<ReturnType<typeof unsubscribe>>, TError = unknown>(
 unsubscribeRequestDto: UnsubscribeRequestDto, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof unsubscribe>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof unsubscribe>>,
          TError,
          Awaited<ReturnType<typeof unsubscribe>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUnsubscribe<TData = Awaited<ReturnType<typeof unsubscribe>>, TError = unknown>(
 unsubscribeRequestDto: UnsubscribeRequestDto, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof unsubscribe>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 웹 푸시 구독 해제
 */

export function useUnsubscribe<TData = Awaited<ReturnType<typeof unsubscribe>>, TError = unknown>(
 unsubscribeRequestDto: UnsubscribeRequestDto, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof unsubscribe>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getUnsubscribeQueryOptions(unsubscribeRequestDto,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * 브라우저 PushSubscription 정보를 등록한다. 이미 등록된 endpoint면 최신 키로 교체된다 (같은 endpoint가 다른 계정으로 재구독되는 경우도 포함). VAPID 키가 설정 안 돼 있어도 요청 자체는 성공하지만, 실제 발송 시점엔 조용히 스킵된다.
 * @summary 웹 푸시 구독 등록
 */
export const subscribe = (
    subscribeRequestDto: SubscribeRequestDto,
 signal?: AbortSignal
) => {


      return orvalMutator<void>(
      {url: `/notifications/subscribe`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: subscribeRequestDto, signal
    },
      );
    }




export const getSubscribeQueryKey = (subscribeRequestDto?: SubscribeRequestDto,) => {
    return [
    'POST', `/notifications/subscribe`, subscribeRequestDto
    ] as const;
    }


export const getSubscribeQueryOptions = <TData = Awaited<ReturnType<typeof subscribe>>, TError = unknown>(subscribeRequestDto: SubscribeRequestDto, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof subscribe>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSubscribeQueryKey(subscribeRequestDto);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof subscribe>>> = ({ signal }) => subscribe(subscribeRequestDto, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof subscribe>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SubscribeQueryResult = NonNullable<Awaited<ReturnType<typeof subscribe>>>
export type SubscribeQueryError = unknown


export function useSubscribe<TData = Awaited<ReturnType<typeof subscribe>>, TError = unknown>(
 subscribeRequestDto: SubscribeRequestDto, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof subscribe>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof subscribe>>,
          TError,
          Awaited<ReturnType<typeof subscribe>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSubscribe<TData = Awaited<ReturnType<typeof subscribe>>, TError = unknown>(
 subscribeRequestDto: SubscribeRequestDto, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof subscribe>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof subscribe>>,
          TError,
          Awaited<ReturnType<typeof subscribe>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSubscribe<TData = Awaited<ReturnType<typeof subscribe>>, TError = unknown>(
 subscribeRequestDto: SubscribeRequestDto, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof subscribe>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 웹 푸시 구독 등록
 */

export function useSubscribe<TData = Awaited<ReturnType<typeof subscribe>>, TError = unknown>(
 subscribeRequestDto: SubscribeRequestDto, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof subscribe>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSubscribeQueryOptions(subscribeRequestDto,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * 본인의 안 읽은 알림을 모두 읽음 처리한다.
 * @summary 전체 읽음 처리
 */
export const readAll = (

 signal?: AbortSignal
) => {


      return orvalMutator<void>(
      {url: `/notifications/read-all`, method: 'POST', signal
    },
      );
    }




export const getReadAllQueryKey = () => {
    return [
    'POST', `/notifications/read-all`
    ] as const;
    }


export const getReadAllQueryOptions = <TData = Awaited<ReturnType<typeof readAll>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readAll>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getReadAllQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof readAll>>> = ({ signal }) => readAll(signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof readAll>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ReadAllQueryResult = NonNullable<Awaited<ReturnType<typeof readAll>>>
export type ReadAllQueryError = unknown


export function useReadAll<TData = Awaited<ReturnType<typeof readAll>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof readAll>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof readAll>>,
          TError,
          Awaited<ReturnType<typeof readAll>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useReadAll<TData = Awaited<ReturnType<typeof readAll>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readAll>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof readAll>>,
          TError,
          Awaited<ReturnType<typeof readAll>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useReadAll<TData = Awaited<ReturnType<typeof readAll>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readAll>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 전체 읽음 처리
 */

export function useReadAll<TData = Awaited<ReturnType<typeof readAll>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readAll>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getReadAllQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * 최신순 커서 페이지네이션. unreadCount는 페이지와 무관하게 전체 안 읽은 개수.
 * @summary 알림 목록 조회
 */
export const getList1 = (
    params?: GetList1Params,
 signal?: AbortSignal
) => {


      return orvalMutator<ApiResponseNotificationListDto>(
      {url: `/notifications`, method: 'GET',
        params, signal
    },
      );
    }




export const getGetList1InfiniteQueryKey = (params?: GetList1Params,) => {
    return [
    'infinite', `/notifications`, ...(params ? [params] : [])
    ] as const;
    }

export const getGetList1QueryKey = (params?: GetList1Params,) => {
    return [
    `/notifications`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetList1InfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getList1>>>, TError = unknown>(params?: GetList1Params, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getList1>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetList1InfiniteQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getList1>>> = ({ signal }) => getList1(params, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getList1>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetList1InfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getList1>>>
export type GetList1InfiniteQueryError = unknown


export function useGetList1Infinite<TData = InfiniteData<Awaited<ReturnType<typeof getList1>>>, TError = unknown>(
 params: undefined |  GetList1Params, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getList1>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getList1>>,
          TError,
          Awaited<ReturnType<typeof getList1>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetList1Infinite<TData = InfiniteData<Awaited<ReturnType<typeof getList1>>>, TError = unknown>(
 params?: GetList1Params, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getList1>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getList1>>,
          TError,
          Awaited<ReturnType<typeof getList1>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetList1Infinite<TData = InfiniteData<Awaited<ReturnType<typeof getList1>>>, TError = unknown>(
 params?: GetList1Params, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getList1>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 알림 목록 조회
 */

export function useGetList1Infinite<TData = InfiniteData<Awaited<ReturnType<typeof getList1>>>, TError = unknown>(
 params?: GetList1Params, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getList1>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetList1InfiniteQueryOptions(params,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getGetList1QueryOptions = <TData = Awaited<ReturnType<typeof getList1>>, TError = unknown>(params?: GetList1Params, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getList1>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetList1QueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getList1>>> = ({ signal }) => getList1(params, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getList1>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetList1QueryResult = NonNullable<Awaited<ReturnType<typeof getList1>>>
export type GetList1QueryError = unknown


export function useGetList1<TData = Awaited<ReturnType<typeof getList1>>, TError = unknown>(
 params: undefined |  GetList1Params, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getList1>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getList1>>,
          TError,
          Awaited<ReturnType<typeof getList1>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetList1<TData = Awaited<ReturnType<typeof getList1>>, TError = unknown>(
 params?: GetList1Params, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getList1>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getList1>>,
          TError,
          Awaited<ReturnType<typeof getList1>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetList1<TData = Awaited<ReturnType<typeof getList1>>, TError = unknown>(
 params?: GetList1Params, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getList1>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 알림 목록 조회
 */

export function useGetList1<TData = Awaited<ReturnType<typeof getList1>>, TError = unknown>(
 params?: GetList1Params, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getList1>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetList1QueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * FE가 pushManager.subscribe({ applicationServerKey })에 넘길 값. 로그인 불필요. VAPID 미설정 환경이면 publicKey가 null로 내려간다 — 이 경우 FE는 푸시 관련 UI 자체를 숨기면 된다.
 * @summary VAPID 공개키 조회
 */
export const getVapidPublicKey = (

 signal?: AbortSignal
) => {


      return orvalMutator<ApiResponseVapidPublicKeyDto>(
      {url: `/notifications/vapid-public-key`, method: 'GET', signal
    },
      );
    }




export const getGetVapidPublicKeyInfiniteQueryKey = () => {
    return [
    'infinite', `/notifications/vapid-public-key`
    ] as const;
    }

export const getGetVapidPublicKeyQueryKey = () => {
    return [
    `/notifications/vapid-public-key`
    ] as const;
    }


export const getGetVapidPublicKeyInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getVapidPublicKey>>>, TError = unknown>( options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getVapidPublicKey>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetVapidPublicKeyInfiniteQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getVapidPublicKey>>> = ({ signal }) => getVapidPublicKey(signal);





   return  { queryKey, queryFn, ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getVapidPublicKey>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetVapidPublicKeyInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getVapidPublicKey>>>
export type GetVapidPublicKeyInfiniteQueryError = unknown


export function useGetVapidPublicKeyInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getVapidPublicKey>>>, TError = unknown>(
  options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getVapidPublicKey>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getVapidPublicKey>>,
          TError,
          Awaited<ReturnType<typeof getVapidPublicKey>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetVapidPublicKeyInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getVapidPublicKey>>>, TError = unknown>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getVapidPublicKey>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getVapidPublicKey>>,
          TError,
          Awaited<ReturnType<typeof getVapidPublicKey>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetVapidPublicKeyInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getVapidPublicKey>>>, TError = unknown>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getVapidPublicKey>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary VAPID 공개키 조회
 */

export function useGetVapidPublicKeyInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getVapidPublicKey>>>, TError = unknown>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getVapidPublicKey>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetVapidPublicKeyInfiniteQueryOptions(options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getGetVapidPublicKeyQueryOptions = <TData = Awaited<ReturnType<typeof getVapidPublicKey>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getVapidPublicKey>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetVapidPublicKeyQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getVapidPublicKey>>> = ({ signal }) => getVapidPublicKey(signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getVapidPublicKey>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetVapidPublicKeyQueryResult = NonNullable<Awaited<ReturnType<typeof getVapidPublicKey>>>
export type GetVapidPublicKeyQueryError = unknown


export function useGetVapidPublicKey<TData = Awaited<ReturnType<typeof getVapidPublicKey>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getVapidPublicKey>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getVapidPublicKey>>,
          TError,
          Awaited<ReturnType<typeof getVapidPublicKey>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetVapidPublicKey<TData = Awaited<ReturnType<typeof getVapidPublicKey>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getVapidPublicKey>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getVapidPublicKey>>,
          TError,
          Awaited<ReturnType<typeof getVapidPublicKey>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetVapidPublicKey<TData = Awaited<ReturnType<typeof getVapidPublicKey>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getVapidPublicKey>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary VAPID 공개키 조회
 */

export function useGetVapidPublicKey<TData = Awaited<ReturnType<typeof getVapidPublicKey>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getVapidPublicKey>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetVapidPublicKeyQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * GNB 배지처럼 목록 없이 숫자만 필요할 때 쓰는 경량 엔드포인트.
 * @summary 안 읽은 알림 개수
 */
export const getUnreadCount = (

 signal?: AbortSignal
) => {


      return orvalMutator<ApiResponseUnreadCountDto>(
      {url: `/notifications/unread-count`, method: 'GET', signal
    },
      );
    }




export const getGetUnreadCountInfiniteQueryKey = () => {
    return [
    'infinite', `/notifications/unread-count`
    ] as const;
    }

export const getGetUnreadCountQueryKey = () => {
    return [
    `/notifications/unread-count`
    ] as const;
    }


export const getGetUnreadCountInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getUnreadCount>>>, TError = unknown>( options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getUnreadCount>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUnreadCountInfiniteQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUnreadCount>>> = ({ signal }) => getUnreadCount(signal);





   return  { queryKey, queryFn, ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getUnreadCount>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetUnreadCountInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getUnreadCount>>>
export type GetUnreadCountInfiniteQueryError = unknown


export function useGetUnreadCountInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getUnreadCount>>>, TError = unknown>(
  options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getUnreadCount>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUnreadCount>>,
          TError,
          Awaited<ReturnType<typeof getUnreadCount>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUnreadCountInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getUnreadCount>>>, TError = unknown>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getUnreadCount>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUnreadCount>>,
          TError,
          Awaited<ReturnType<typeof getUnreadCount>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUnreadCountInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getUnreadCount>>>, TError = unknown>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getUnreadCount>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 안 읽은 알림 개수
 */

export function useGetUnreadCountInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getUnreadCount>>>, TError = unknown>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getUnreadCount>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetUnreadCountInfiniteQueryOptions(options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getGetUnreadCountQueryOptions = <TData = Awaited<ReturnType<typeof getUnreadCount>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUnreadCount>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUnreadCountQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUnreadCount>>> = ({ signal }) => getUnreadCount(signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getUnreadCount>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetUnreadCountQueryResult = NonNullable<Awaited<ReturnType<typeof getUnreadCount>>>
export type GetUnreadCountQueryError = unknown


export function useGetUnreadCount<TData = Awaited<ReturnType<typeof getUnreadCount>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUnreadCount>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUnreadCount>>,
          TError,
          Awaited<ReturnType<typeof getUnreadCount>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUnreadCount<TData = Awaited<ReturnType<typeof getUnreadCount>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUnreadCount>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUnreadCount>>,
          TError,
          Awaited<ReturnType<typeof getUnreadCount>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUnreadCount<TData = Awaited<ReturnType<typeof getUnreadCount>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUnreadCount>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 안 읽은 알림 개수
 */

export function useGetUnreadCount<TData = Awaited<ReturnType<typeof getUnreadCount>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUnreadCount>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetUnreadCountQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * 이 유저의 계정에 등록된 구독을 전부 반환한다. endpoint/암호화 키는 노출하지 않고, 구독 당시 User-Agent 원문과 등록 시각만 내려준다.
 * @summary 등록된 웹 푸시 구독(기기) 목록
 */
export const getSubscriptions = (

 signal?: AbortSignal
) => {


      return orvalMutator<ApiResponseListPushSubscriptionDto>(
      {url: `/notifications/subscriptions`, method: 'GET', signal
    },
      );
    }




export const getGetSubscriptionsInfiniteQueryKey = () => {
    return [
    'infinite', `/notifications/subscriptions`
    ] as const;
    }

export const getGetSubscriptionsQueryKey = () => {
    return [
    `/notifications/subscriptions`
    ] as const;
    }


export const getGetSubscriptionsInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getSubscriptions>>>, TError = unknown>( options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getSubscriptions>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetSubscriptionsInfiniteQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getSubscriptions>>> = ({ signal }) => getSubscriptions(signal);





   return  { queryKey, queryFn, ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getSubscriptions>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetSubscriptionsInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getSubscriptions>>>
export type GetSubscriptionsInfiniteQueryError = unknown


export function useGetSubscriptionsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getSubscriptions>>>, TError = unknown>(
  options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getSubscriptions>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSubscriptions>>,
          TError,
          Awaited<ReturnType<typeof getSubscriptions>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSubscriptionsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getSubscriptions>>>, TError = unknown>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getSubscriptions>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSubscriptions>>,
          TError,
          Awaited<ReturnType<typeof getSubscriptions>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSubscriptionsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getSubscriptions>>>, TError = unknown>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getSubscriptions>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 등록된 웹 푸시 구독(기기) 목록
 */

export function useGetSubscriptionsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getSubscriptions>>>, TError = unknown>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getSubscriptions>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetSubscriptionsInfiniteQueryOptions(options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getGetSubscriptionsQueryOptions = <TData = Awaited<ReturnType<typeof getSubscriptions>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSubscriptions>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetSubscriptionsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getSubscriptions>>> = ({ signal }) => getSubscriptions(signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getSubscriptions>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetSubscriptionsQueryResult = NonNullable<Awaited<ReturnType<typeof getSubscriptions>>>
export type GetSubscriptionsQueryError = unknown


export function useGetSubscriptions<TData = Awaited<ReturnType<typeof getSubscriptions>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSubscriptions>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSubscriptions>>,
          TError,
          Awaited<ReturnType<typeof getSubscriptions>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSubscriptions<TData = Awaited<ReturnType<typeof getSubscriptions>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSubscriptions>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSubscriptions>>,
          TError,
          Awaited<ReturnType<typeof getSubscriptions>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSubscriptions<TData = Awaited<ReturnType<typeof getSubscriptions>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSubscriptions>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 등록된 웹 푸시 구독(기기) 목록
 */

export function useGetSubscriptions<TData = Awaited<ReturnType<typeof getSubscriptions>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSubscriptions>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetSubscriptionsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * GET /notifications/subscriptions 목록에서 본 id로 그 기기 하나만 콕 집어 해지한다. /unsubscribe(endpoint 기준)와 달리, 지금 요청을 보내는 브라우저가 그 기기가 아니어도 된다 — 예: PC 설정 화면에서 예전에 등록해둔 폰 구독을 끄는 경우.
 * @summary 특정 웹 푸시 구독(기기) 해제
 */
export const deleteSubscription = (
    id: number,
 signal?: AbortSignal
) => {


      return orvalMutator<void>(
      {url: `/notifications/subscriptions/${id}`, method: 'DELETE', signal
    },
      );
    }




export const getDeleteSubscriptionQueryKey = (id: number,) => {
    return [
    'DELETE', `/notifications/subscriptions/${id}`
    ] as const;
    }


export const getDeleteSubscriptionQueryOptions = <TData = Awaited<ReturnType<typeof deleteSubscription>>, TError = unknown>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deleteSubscription>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDeleteSubscriptionQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof deleteSubscription>>> = ({ signal }) => deleteSubscription(id, signal);





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof deleteSubscription>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type DeleteSubscriptionQueryResult = NonNullable<Awaited<ReturnType<typeof deleteSubscription>>>
export type DeleteSubscriptionQueryError = unknown


export function useDeleteSubscription<TData = Awaited<ReturnType<typeof deleteSubscription>>, TError = unknown>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof deleteSubscription>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof deleteSubscription>>,
          TError,
          Awaited<ReturnType<typeof deleteSubscription>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDeleteSubscription<TData = Awaited<ReturnType<typeof deleteSubscription>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deleteSubscription>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof deleteSubscription>>,
          TError,
          Awaited<ReturnType<typeof deleteSubscription>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDeleteSubscription<TData = Awaited<ReturnType<typeof deleteSubscription>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deleteSubscription>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 특정 웹 푸시 구독(기기) 해제
 */

export function useDeleteSubscription<TData = Awaited<ReturnType<typeof deleteSubscription>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deleteSubscription>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getDeleteSubscriptionQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






