/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Tripbite api
 * OpenAPI spec version: v1.0.0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  ApiResponseListPushSubscriptionDto,
  ApiResponseNotificationListDto,
  ApiResponseUnreadCountDto,
  ApiResponseVapidPublicKeyDto,
  NotificationListDto,
  UnreadCountDto,
  VapidPublicKeyDto
} from '../schemas';


export const getGetList1ResponseNotificationListDtoMock = (overrideResponse: Partial<NotificationListDto> = {}): NotificationListDto => ({...{items: faker.helpers.arrayElement([Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => ({id: faker.helpers.arrayElement([faker.number.int(), undefined]), type: faker.helpers.arrayElement([faker.helpers.arrayElement(['letter.received','letter.liked','letter.delivered','tournament.shared','event','security'] as const), undefined]), title: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), body: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), undefined]), link: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), undefined]), read: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]), createdAt: faker.helpers.arrayElement([faker.date.past().toISOString().slice(0, 19) + 'Z', undefined])})), undefined]), unreadCount: faker.helpers.arrayElement([faker.number.int(), undefined]), nextCursor: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.number.int(), null]), undefined])}, ...overrideResponse});

export const getGetList1ResponseMock = (overrideResponse: Partial<Extract<ApiResponseNotificationListDto, object>> = {}): ApiResponseNotificationListDto => ({success: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]), message: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), undefined]), data: faker.helpers.arrayElement([faker.helpers.arrayElement([{...getGetList1ResponseNotificationListDtoMock()},null,]), undefined]), ...overrideResponse})

export const getGetVapidPublicKeyResponseVapidPublicKeyDtoMock = (overrideResponse: Partial<VapidPublicKeyDto> = {}): VapidPublicKeyDto => ({...{publicKey: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), undefined])}, ...overrideResponse});

export const getGetVapidPublicKeyResponseMock = (overrideResponse: Partial<Extract<ApiResponseVapidPublicKeyDto, object>> = {}): ApiResponseVapidPublicKeyDto => ({success: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]), message: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), undefined]), data: faker.helpers.arrayElement([faker.helpers.arrayElement([{...getGetVapidPublicKeyResponseVapidPublicKeyDtoMock()},null,]), undefined]), ...overrideResponse})

export const getGetUnreadCountResponseUnreadCountDtoMock = (overrideResponse: Partial<UnreadCountDto> = {}): UnreadCountDto => ({...{unreadCount: faker.helpers.arrayElement([faker.number.int(), undefined])}, ...overrideResponse});

export const getGetUnreadCountResponseMock = (overrideResponse: Partial<Extract<ApiResponseUnreadCountDto, object>> = {}): ApiResponseUnreadCountDto => ({success: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]), message: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), undefined]), data: faker.helpers.arrayElement([faker.helpers.arrayElement([{...getGetUnreadCountResponseUnreadCountDtoMock()},null,]), undefined]), ...overrideResponse})

export const getGetSubscriptionsResponseMock = (overrideResponse: Partial<Extract<ApiResponseListPushSubscriptionDto, object>> = {}): ApiResponseListPushSubscriptionDto => ({success: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]), message: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), undefined]), data: faker.helpers.arrayElement([Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => ({id: faker.helpers.arrayElement([faker.number.int(), undefined]), userAgent: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), undefined]), createdAt: faker.helpers.arrayElement([faker.date.past().toISOString().slice(0, 19) + 'Z', undefined])})), undefined]), ...overrideResponse})


export const getReadMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.post('*/notifications/:id/read', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }

    return new HttpResponse(null,
      { status: 200
      })
  }, options)
}

export const getUnsubscribeMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.post('*/notifications/unsubscribe', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }

    return new HttpResponse(null,
      { status: 200
      })
  }, options)
}

export const getSubscribeMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.post('*/notifications/subscribe', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }

    return new HttpResponse(null,
      { status: 200
      })
  }, options)
}

export const getReadAllMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.post('*/notifications/read-all', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }

    return new HttpResponse(null,
      { status: 200
      })
  }, options)
}

export const getGetList1MockHandler = (overrideResponse?: ApiResponseNotificationListDto | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<ApiResponseNotificationListDto> | ApiResponseNotificationListDto), options?: RequestHandlerOptions) => {
  return http.get('*/notifications', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetList1ResponseMock(),
      { status: 200
      })
  }, options)
}

export const getGetVapidPublicKeyMockHandler = (overrideResponse?: ApiResponseVapidPublicKeyDto | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<ApiResponseVapidPublicKeyDto> | ApiResponseVapidPublicKeyDto), options?: RequestHandlerOptions) => {
  return http.get('*/notifications/vapid-public-key', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetVapidPublicKeyResponseMock(),
      { status: 200
      })
  }, options)
}

export const getGetUnreadCountMockHandler = (overrideResponse?: ApiResponseUnreadCountDto | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<ApiResponseUnreadCountDto> | ApiResponseUnreadCountDto), options?: RequestHandlerOptions) => {
  return http.get('*/notifications/unread-count', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetUnreadCountResponseMock(),
      { status: 200
      })
  }, options)
}

export const getGetSubscriptionsMockHandler = (overrideResponse?: ApiResponseListPushSubscriptionDto | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<ApiResponseListPushSubscriptionDto> | ApiResponseListPushSubscriptionDto), options?: RequestHandlerOptions) => {
  return http.get('*/notifications/subscriptions', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetSubscriptionsResponseMock(),
      { status: 200
      })
  }, options)
}

export const getDeleteSubscriptionMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.delete('*/notifications/subscriptions/:id', async (info: Parameters<Parameters<typeof http.delete>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }

    return new HttpResponse(null,
      { status: 200
      })
  }, options)
}
export const getNotificationMock = () => [
  getReadMockHandler(),
  getUnsubscribeMockHandler(),
  getSubscribeMockHandler(),
  getReadAllMockHandler(),
  getGetList1MockHandler(),
  getGetVapidPublicKeyMockHandler(),
  getGetUnreadCountMockHandler(),
  getGetSubscriptionsMockHandler(),
  getDeleteSubscriptionMockHandler()
]
