/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import { useInfiniteQuery, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  ApiResponseListSavedTournamentDto,
  ApiResponseListTournamentSummaryDto,
  ApiResponseSavedTournamentDto,
  ApiResponseStampsDto,
  ApiResponseTournamentSummaryDto,
  RecordTournamentRequestDto,
  SaveTournamentRequestDto,
} from '../schemas';

import { orvalMutator } from '../../../services/api/orval-mutator';

/**
 * 내가 저장한 우승지를 최신순으로 전부 반환한다 (최대 20개라 별도 페이지네이션 없음).
 * @summary 저장한 우승지 목록 조회
 */
export const getList = (signal?: AbortSignal) => {
  return orvalMutator<ApiResponseListSavedTournamentDto>({
    url: `/mypage/tournaments`,
    method: 'GET',
    signal,
  });
};

export const getGetListInfiniteQueryKey = () => {
  return ['infinite', `/mypage/tournaments`] as const;
};

export const getGetListQueryKey = () => {
  return [`/mypage/tournaments`] as const;
};

export const getGetListInfiniteQueryOptions = <
  TData = InfiniteData<Awaited<ReturnType<typeof getList>>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseInfiniteQueryOptions<Awaited<ReturnType<typeof getList>>, TError, TData>
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetListInfiniteQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getList>>> = ({
    signal,
  }) => getList(signal);

  return { queryKey, queryFn, ...queryOptions } as UseInfiniteQueryOptions<
    Awaited<ReturnType<typeof getList>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetListInfiniteQueryResult = NonNullable<
  Awaited<ReturnType<typeof getList>>
>;
export type GetListInfiniteQueryError = unknown;

export function useGetListInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getList>>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getList>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getList>>,
          TError,
          Awaited<ReturnType<typeof getList>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseInfiniteQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetListInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getList>>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getList>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getList>>,
          TError,
          Awaited<ReturnType<typeof getList>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetListInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getList>>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getList>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 저장한 우승지 목록 조회
 */

export function useGetListInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getList>>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getList>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetListInfiniteQueryOptions(options);

  const query = useInfiniteQuery(
    queryOptions,
    queryClient,
  ) as UseInfiniteQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

export const getGetListQueryOptions = <
  TData = Awaited<ReturnType<typeof getList>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getList>>, TError, TData>
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetListQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getList>>> = ({
    signal,
  }) => getList(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getList>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetListQueryResult = NonNullable<
  Awaited<ReturnType<typeof getList>>
>;
export type GetListQueryError = unknown;

export function useGetList<
  TData = Awaited<ReturnType<typeof getList>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getList>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getList>>,
          TError,
          Awaited<ReturnType<typeof getList>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetList<
  TData = Awaited<ReturnType<typeof getList>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getList>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getList>>,
          TError,
          Awaited<ReturnType<typeof getList>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetList<
  TData = Awaited<ReturnType<typeof getList>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getList>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 저장한 우승지 목록 조회
 */

export function useGetList<
  TData = Awaited<ReturnType<typeof getList>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getList>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetListQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * destinationId만 넘기면 서버가 여행지의 이름/카테고리/지역/주소/이미지를 조회해 함께 스냅샷으로 저장한다. 유저당 최대 20개까지 저장 가능 — 초과 시 409 SAVED_LIMIT_REACHED.
 * @summary 우승지 저장
 */
export const save = (
  saveTournamentRequestDto: SaveTournamentRequestDto,
  signal?: AbortSignal,
) => {
  return orvalMutator<ApiResponseSavedTournamentDto>({
    url: `/mypage/tournaments`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: saveTournamentRequestDto,
    signal,
  });
};

export const getSaveQueryKey = (
  saveTournamentRequestDto?: SaveTournamentRequestDto,
) => {
  return ['POST', `/mypage/tournaments`, saveTournamentRequestDto] as const;
};

export const getSaveQueryOptions = <
  TData = Awaited<ReturnType<typeof save>>,
  TError = unknown,
>(
  saveTournamentRequestDto: SaveTournamentRequestDto,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof save>>, TError, TData>
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getSaveQueryKey(saveTournamentRequestDto);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof save>>> = ({
    signal,
  }) => save(saveTournamentRequestDto, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof save>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type SaveQueryResult = NonNullable<Awaited<ReturnType<typeof save>>>;
export type SaveQueryError = unknown;

export function useSave<
  TData = Awaited<ReturnType<typeof save>>,
  TError = unknown,
>(
  saveTournamentRequestDto: SaveTournamentRequestDto,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof save>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof save>>,
          TError,
          Awaited<ReturnType<typeof save>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useSave<
  TData = Awaited<ReturnType<typeof save>>,
  TError = unknown,
>(
  saveTournamentRequestDto: SaveTournamentRequestDto,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof save>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof save>>,
          TError,
          Awaited<ReturnType<typeof save>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useSave<
  TData = Awaited<ReturnType<typeof save>>,
  TError = unknown,
>(
  saveTournamentRequestDto: SaveTournamentRequestDto,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof save>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 우승지 저장
 */

export function useSave<
  TData = Awaited<ReturnType<typeof save>>,
  TError = unknown,
>(
  saveTournamentRequestDto: SaveTournamentRequestDto,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof save>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getSaveQueryOptions(saveTournamentRequestDto, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * 내가 완료한 토너먼트를 최신순으로 최대 10개까지 반환한다 (전체보기/페이지네이션 없음).
 * @summary 최근 토너먼트 목록
 */
export const getRecentTournaments = (signal?: AbortSignal) => {
  return orvalMutator<ApiResponseListTournamentSummaryDto>({
    url: `/mypage/tournament-history`,
    method: 'GET',
    signal,
  });
};

export const getGetRecentTournamentsInfiniteQueryKey = () => {
  return ['infinite', `/mypage/tournament-history`] as const;
};

export const getGetRecentTournamentsQueryKey = () => {
  return [`/mypage/tournament-history`] as const;
};

export const getGetRecentTournamentsInfiniteQueryOptions = <
  TData = InfiniteData<Awaited<ReturnType<typeof getRecentTournaments>>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseInfiniteQueryOptions<
      Awaited<ReturnType<typeof getRecentTournaments>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetRecentTournamentsInfiniteQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getRecentTournaments>>
  > = ({ signal }) => getRecentTournaments(signal);

  return { queryKey, queryFn, ...queryOptions } as UseInfiniteQueryOptions<
    Awaited<ReturnType<typeof getRecentTournaments>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetRecentTournamentsInfiniteQueryResult = NonNullable<
  Awaited<ReturnType<typeof getRecentTournaments>>
>;
export type GetRecentTournamentsInfiniteQueryError = unknown;

export function useGetRecentTournamentsInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getRecentTournaments>>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getRecentTournaments>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRecentTournaments>>,
          TError,
          Awaited<ReturnType<typeof getRecentTournaments>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseInfiniteQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetRecentTournamentsInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getRecentTournaments>>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getRecentTournaments>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRecentTournaments>>,
          TError,
          Awaited<ReturnType<typeof getRecentTournaments>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetRecentTournamentsInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getRecentTournaments>>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getRecentTournaments>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 최근 토너먼트 목록
 */

export function useGetRecentTournamentsInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getRecentTournaments>>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getRecentTournaments>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetRecentTournamentsInfiniteQueryOptions(options);

  const query = useInfiniteQuery(
    queryOptions,
    queryClient,
  ) as UseInfiniteQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

export const getGetRecentTournamentsQueryOptions = <
  TData = Awaited<ReturnType<typeof getRecentTournaments>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getRecentTournaments>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetRecentTournamentsQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getRecentTournaments>>
  > = ({ signal }) => getRecentTournaments(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getRecentTournaments>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetRecentTournamentsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getRecentTournaments>>
>;
export type GetRecentTournamentsQueryError = unknown;

export function useGetRecentTournaments<
  TData = Awaited<ReturnType<typeof getRecentTournaments>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getRecentTournaments>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRecentTournaments>>,
          TError,
          Awaited<ReturnType<typeof getRecentTournaments>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetRecentTournaments<
  TData = Awaited<ReturnType<typeof getRecentTournaments>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getRecentTournaments>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRecentTournaments>>,
          TError,
          Awaited<ReturnType<typeof getRecentTournaments>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetRecentTournaments<
  TData = Awaited<ReturnType<typeof getRecentTournaments>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getRecentTournaments>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 최근 토너먼트 목록
 */

export function useGetRecentTournaments<
  TData = Awaited<ReturnType<typeof getRecentTournaments>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getRecentTournaments>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetRecentTournamentsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * 토너먼트 우승자가 결정되면 이 API로 결과를 기록한다. winnerId는 GET /destinations/random으로 받은 항목의 id(TourAPI contentId).
 * @summary 토너먼트 결과 기록
 */
export const recordTournament = (
  recordTournamentRequestDto: RecordTournamentRequestDto,
  signal?: AbortSignal,
) => {
  return orvalMutator<ApiResponseTournamentSummaryDto>({
    url: `/mypage/tournament-history`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: recordTournamentRequestDto,
    signal,
  });
};

export const getRecordTournamentQueryKey = (
  recordTournamentRequestDto?: RecordTournamentRequestDto,
) => {
  return [
    'POST',
    `/mypage/tournament-history`,
    recordTournamentRequestDto,
  ] as const;
};

export const getRecordTournamentQueryOptions = <
  TData = Awaited<ReturnType<typeof recordTournament>>,
  TError = unknown,
>(
  recordTournamentRequestDto: RecordTournamentRequestDto,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof recordTournament>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getRecordTournamentQueryKey(recordTournamentRequestDto);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof recordTournament>>
  > = ({ signal }) => recordTournament(recordTournamentRequestDto, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof recordTournament>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type RecordTournamentQueryResult = NonNullable<
  Awaited<ReturnType<typeof recordTournament>>
>;
export type RecordTournamentQueryError = unknown;

export function useRecordTournament<
  TData = Awaited<ReturnType<typeof recordTournament>>,
  TError = unknown,
>(
  recordTournamentRequestDto: RecordTournamentRequestDto,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof recordTournament>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof recordTournament>>,
          TError,
          Awaited<ReturnType<typeof recordTournament>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useRecordTournament<
  TData = Awaited<ReturnType<typeof recordTournament>>,
  TError = unknown,
>(
  recordTournamentRequestDto: RecordTournamentRequestDto,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof recordTournament>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof recordTournament>>,
          TError,
          Awaited<ReturnType<typeof recordTournament>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useRecordTournament<
  TData = Awaited<ReturnType<typeof recordTournament>>,
  TError = unknown,
>(
  recordTournamentRequestDto: RecordTournamentRequestDto,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof recordTournament>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 토너먼트 결과 기록
 */

export function useRecordTournament<
  TData = Awaited<ReturnType<typeof recordTournament>>,
  TError = unknown,
>(
  recordTournamentRequestDto: RecordTournamentRequestDto,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof recordTournament>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getRecordTournamentQueryOptions(
    recordTournamentRequestDto,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * 내가 우승 기록을 남긴 지역(시/군) 목록과 충북 전체 지역 수(11)를 반환한다. "충북 마스터" 여부는 visited.size == total로 계산할 수 있다.
 * @summary 충북 도장책 조회
 */
export const getStamps = (signal?: AbortSignal) => {
  return orvalMutator<ApiResponseStampsDto>({
    url: `/mypage/stamps`,
    method: 'GET',
    signal,
  });
};

export const getGetStampsInfiniteQueryKey = () => {
  return ['infinite', `/mypage/stamps`] as const;
};

export const getGetStampsQueryKey = () => {
  return [`/mypage/stamps`] as const;
};

export const getGetStampsInfiniteQueryOptions = <
  TData = InfiniteData<Awaited<ReturnType<typeof getStamps>>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseInfiniteQueryOptions<
      Awaited<ReturnType<typeof getStamps>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetStampsInfiniteQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getStamps>>> = ({
    signal,
  }) => getStamps(signal);

  return { queryKey, queryFn, ...queryOptions } as UseInfiniteQueryOptions<
    Awaited<ReturnType<typeof getStamps>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetStampsInfiniteQueryResult = NonNullable<
  Awaited<ReturnType<typeof getStamps>>
>;
export type GetStampsInfiniteQueryError = unknown;

export function useGetStampsInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getStamps>>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getStamps>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStamps>>,
          TError,
          Awaited<ReturnType<typeof getStamps>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseInfiniteQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetStampsInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getStamps>>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getStamps>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStamps>>,
          TError,
          Awaited<ReturnType<typeof getStamps>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetStampsInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getStamps>>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getStamps>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 충북 도장책 조회
 */

export function useGetStampsInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getStamps>>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getStamps>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetStampsInfiniteQueryOptions(options);

  const query = useInfiniteQuery(
    queryOptions,
    queryClient,
  ) as UseInfiniteQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

export const getGetStampsQueryOptions = <
  TData = Awaited<ReturnType<typeof getStamps>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getStamps>>, TError, TData>
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetStampsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getStamps>>> = ({
    signal,
  }) => getStamps(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getStamps>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetStampsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getStamps>>
>;
export type GetStampsQueryError = unknown;

export function useGetStamps<
  TData = Awaited<ReturnType<typeof getStamps>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getStamps>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStamps>>,
          TError,
          Awaited<ReturnType<typeof getStamps>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetStamps<
  TData = Awaited<ReturnType<typeof getStamps>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getStamps>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStamps>>,
          TError,
          Awaited<ReturnType<typeof getStamps>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetStamps<
  TData = Awaited<ReturnType<typeof getStamps>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getStamps>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 충북 도장책 조회
 */

export function useGetStamps<
  TData = Awaited<ReturnType<typeof getStamps>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getStamps>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetStampsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * id는 저장 응답/목록의 id(저장 레코드 id)를 그대로 사용한다.
 * @summary 저장한 우승지 삭제
 */
export const delete1 = (id: number, signal?: AbortSignal) => {
  return orvalMutator<void>({
    url: `/mypage/tournaments/${id}`,
    method: 'DELETE',
    signal,
  });
};

export const getDelete1QueryKey = (id: number) => {
  return ['DELETE', `/mypage/tournaments/${id}`] as const;
};

export const getDelete1QueryOptions = <
  TData = Awaited<ReturnType<typeof delete1>>,
  TError = unknown,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof delete1>>, TError, TData>
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getDelete1QueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof delete1>>> = ({
    signal,
  }) => delete1(id, signal);

  return {
    queryKey,
    queryFn,
    enabled: id !== null && id !== undefined,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof delete1>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type Delete1QueryResult = NonNullable<
  Awaited<ReturnType<typeof delete1>>
>;
export type Delete1QueryError = unknown;

export function useDelete1<
  TData = Awaited<ReturnType<typeof delete1>>,
  TError = unknown,
>(
  id: number,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof delete1>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof delete1>>,
          TError,
          Awaited<ReturnType<typeof delete1>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useDelete1<
  TData = Awaited<ReturnType<typeof delete1>>,
  TError = unknown,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof delete1>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof delete1>>,
          TError,
          Awaited<ReturnType<typeof delete1>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useDelete1<
  TData = Awaited<ReturnType<typeof delete1>>,
  TError = unknown,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof delete1>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 저장한 우승지 삭제
 */

export function useDelete1<
  TData = Awaited<ReturnType<typeof delete1>>,
  TError = unknown,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof delete1>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getDelete1QueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
