/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import { faker } from '@faker-js/faker';

import { HttpResponse, http } from 'msw';
import type { RequestHandlerOptions } from 'msw';

import type {
  ApiResponseListSavedTournamentDto,
  ApiResponseListTournamentSummaryDto,
  ApiResponseSavedTournamentDto,
  ApiResponseStampsDto,
  ApiResponseTournamentSummaryDto,
  SavedTournamentDto,
  StampsDto,
  TournamentSummaryDto,
} from '../schemas';

export const getGetListResponseMock = (
  overrideResponse: Partial<
    Extract<ApiResponseListSavedTournamentDto, object>
  > = {},
): ApiResponseListSavedTournamentDto => ({
  success: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
  message: faker.helpers.arrayElement([
    faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      null,
    ]),
    undefined,
  ]),
  data: faker.helpers.arrayElement([
    Array.from(
      { length: faker.number.int({ min: 1, max: 10 }) },
      (_, i) => i + 1,
    ).map(() => ({
      id: faker.helpers.arrayElement([faker.number.int(), undefined]),
      destination: faker.helpers.arrayElement([
        {
          id: faker.helpers.arrayElement([faker.number.int(), undefined]),
          name: faker.helpers.arrayElement([
            faker.string.alpha({ length: { min: 10, max: 20 } }),
            undefined,
          ]),
          category: faker.helpers.arrayElement([
            faker.helpers.arrayElement([
              'attraction',
              'festival',
              'experience',
            ] as const),
            undefined,
          ]),
          region: faker.helpers.arrayElement([
            faker.helpers.arrayElement([
              faker.helpers.arrayElement([
                'cheongju',
                'chungju',
                'jecheon',
                'boeun',
                'okcheon',
                'yeongdong',
                'jincheon',
                'goesan',
                'eumseong',
                'danyang',
                'jeungpyeong',
              ] as const),
              null,
            ]),
            undefined,
          ]),
          address: faker.helpers.arrayElement([
            faker.string.alpha({ length: { min: 10, max: 20 } }),
            undefined,
          ]),
          imageUrl: faker.helpers.arrayElement([
            faker.helpers.arrayElement([
              faker.string.alpha({ length: { min: 10, max: 20 } }),
              null,
            ]),
            undefined,
          ]),
        },
        undefined,
      ]),
      savedAt: faker.helpers.arrayElement([
        faker.date.past().toISOString().slice(0, 19) + 'Z',
        undefined,
      ]),
    })),
    undefined,
  ]),
  ...overrideResponse,
});

export const getSaveResponseSavedTournamentDtoMock = (
  overrideResponse: Partial<SavedTournamentDto> = {},
): SavedTournamentDto => ({
  ...{
    id: faker.helpers.arrayElement([faker.number.int(), undefined]),
    destination: faker.helpers.arrayElement([
      {
        id: faker.helpers.arrayElement([faker.number.int(), undefined]),
        name: faker.helpers.arrayElement([
          faker.string.alpha({ length: { min: 10, max: 20 } }),
          undefined,
        ]),
        category: faker.helpers.arrayElement([
          faker.helpers.arrayElement([
            'attraction',
            'festival',
            'experience',
          ] as const),
          undefined,
        ]),
        region: faker.helpers.arrayElement([
          faker.helpers.arrayElement([
            faker.helpers.arrayElement([
              'cheongju',
              'chungju',
              'jecheon',
              'boeun',
              'okcheon',
              'yeongdong',
              'jincheon',
              'goesan',
              'eumseong',
              'danyang',
              'jeungpyeong',
            ] as const),
            null,
          ]),
          undefined,
        ]),
        address: faker.helpers.arrayElement([
          faker.string.alpha({ length: { min: 10, max: 20 } }),
          undefined,
        ]),
        imageUrl: faker.helpers.arrayElement([
          faker.helpers.arrayElement([
            faker.string.alpha({ length: { min: 10, max: 20 } }),
            null,
          ]),
          undefined,
        ]),
      },
      undefined,
    ]),
    savedAt: faker.helpers.arrayElement([
      faker.date.past().toISOString().slice(0, 19) + 'Z',
      undefined,
    ]),
  },
  ...overrideResponse,
});

export const getSaveResponseMock = (
  overrideResponse: Partial<
    Extract<ApiResponseSavedTournamentDto, object>
  > = {},
): ApiResponseSavedTournamentDto => ({
  success: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
  message: faker.helpers.arrayElement([
    faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      null,
    ]),
    undefined,
  ]),
  data: faker.helpers.arrayElement([
    faker.helpers.arrayElement([
      { ...getSaveResponseSavedTournamentDtoMock() },
      null,
    ]),
    undefined,
  ]),
  ...overrideResponse,
});

export const getGetRecentTournamentsResponseMock = (
  overrideResponse: Partial<
    Extract<ApiResponseListTournamentSummaryDto, object>
  > = {},
): ApiResponseListTournamentSummaryDto => ({
  success: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
  message: faker.helpers.arrayElement([
    faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      null,
    ]),
    undefined,
  ]),
  data: faker.helpers.arrayElement([
    Array.from(
      { length: faker.number.int({ min: 1, max: 10 }) },
      (_, i) => i + 1,
    ).map(() => ({
      id: faker.helpers.arrayElement([faker.number.int(), undefined]),
      winnerName: faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        undefined,
      ]),
      tournamentSize: faker.helpers.arrayElement([
        faker.number.int(),
        undefined,
      ]),
      category: faker.helpers.arrayElement([
        faker.helpers.arrayElement([
          'attraction',
          'festival',
          'experience',
        ] as const),
        undefined,
      ]),
      completedAt: faker.helpers.arrayElement([
        faker.date.past().toISOString().slice(0, 19) + 'Z',
        undefined,
      ]),
    })),
    undefined,
  ]),
  ...overrideResponse,
});

export const getRecordTournamentResponseTournamentSummaryDtoMock = (
  overrideResponse: Partial<TournamentSummaryDto> = {},
): TournamentSummaryDto => ({
  ...{
    id: faker.helpers.arrayElement([faker.number.int(), undefined]),
    winnerName: faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      undefined,
    ]),
    tournamentSize: faker.helpers.arrayElement([faker.number.int(), undefined]),
    category: faker.helpers.arrayElement([
      faker.helpers.arrayElement([
        'attraction',
        'festival',
        'experience',
      ] as const),
      undefined,
    ]),
    completedAt: faker.helpers.arrayElement([
      faker.date.past().toISOString().slice(0, 19) + 'Z',
      undefined,
    ]),
  },
  ...overrideResponse,
});

export const getRecordTournamentResponseMock = (
  overrideResponse: Partial<
    Extract<ApiResponseTournamentSummaryDto, object>
  > = {},
): ApiResponseTournamentSummaryDto => ({
  success: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
  message: faker.helpers.arrayElement([
    faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      null,
    ]),
    undefined,
  ]),
  data: faker.helpers.arrayElement([
    faker.helpers.arrayElement([
      { ...getRecordTournamentResponseTournamentSummaryDtoMock() },
      null,
    ]),
    undefined,
  ]),
  ...overrideResponse,
});

export const getGetStampsResponseStampsDtoMock = (
  overrideResponse: Partial<StampsDto> = {},
): StampsDto => ({
  ...{
    visited: faker.helpers.arrayElement([
      faker.helpers.arrayElements([
        'cheongju',
        'chungju',
        'jecheon',
        'boeun',
        'okcheon',
        'yeongdong',
        'jincheon',
        'goesan',
        'eumseong',
        'danyang',
        'jeungpyeong',
      ] as const),
      undefined,
    ]),
    total: faker.helpers.arrayElement([faker.number.int(), undefined]),
  },
  ...overrideResponse,
});

export const getGetStampsResponseMock = (
  overrideResponse: Partial<Extract<ApiResponseStampsDto, object>> = {},
): ApiResponseStampsDto => ({
  success: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
  message: faker.helpers.arrayElement([
    faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      null,
    ]),
    undefined,
  ]),
  data: faker.helpers.arrayElement([
    faker.helpers.arrayElement([
      { ...getGetStampsResponseStampsDtoMock() },
      null,
    ]),
    undefined,
  ]),
  ...overrideResponse,
});

export const getGetListMockHandler = (
  overrideResponse?:
    | ApiResponseListSavedTournamentDto
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) =>
        | Promise<ApiResponseListSavedTournamentDto>
        | ApiResponseListSavedTournamentDto),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    '*/mypage/tournaments',
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getGetListResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};

export const getSaveMockHandler = (
  overrideResponse?:
    | ApiResponseSavedTournamentDto
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) =>
        | Promise<ApiResponseSavedTournamentDto>
        | ApiResponseSavedTournamentDto),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    '*/mypage/tournaments',
    async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getSaveResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};

export const getGetRecentTournamentsMockHandler = (
  overrideResponse?:
    | ApiResponseListTournamentSummaryDto
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) =>
        | Promise<ApiResponseListTournamentSummaryDto>
        | ApiResponseListTournamentSummaryDto),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    '*/mypage/tournament-history',
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getGetRecentTournamentsResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};

export const getRecordTournamentMockHandler = (
  overrideResponse?:
    | ApiResponseTournamentSummaryDto
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) =>
        | Promise<ApiResponseTournamentSummaryDto>
        | ApiResponseTournamentSummaryDto),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    '*/mypage/tournament-history',
    async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getRecordTournamentResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};

export const getGetStampsMockHandler = (
  overrideResponse?:
    | ApiResponseStampsDto
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<ApiResponseStampsDto> | ApiResponseStampsDto),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    '*/mypage/stamps',
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getGetStampsResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};

export const getDelete1MockHandler = (
  overrideResponse?:
    | void
    | ((
        info: Parameters<Parameters<typeof http.delete>[1]>[0],
      ) => Promise<void> | void),
  options?: RequestHandlerOptions,
) => {
  return http.delete(
    '*/mypage/tournaments/:id',
    async (info: Parameters<Parameters<typeof http.delete>[1]>[0]) => {
      if (typeof overrideResponse === 'function') {
        await overrideResponse(info);
      }

      return new HttpResponse(null, { status: 200 });
    },
    options,
  );
};
export const getMypageMock = () => [
  getGetListMockHandler(),
  getSaveMockHandler(),
  getGetRecentTournamentsMockHandler(),
  getRecordTournamentMockHandler(),
  getGetStampsMockHandler(),
  getDelete1MockHandler(),
];
