/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  ApiResponseQuizDto,
  ApiResponseTravelTypeResultDto,
  QuizDto,
  TravelTypeResultDto
} from '../schemas';


export const getSubmitResponseTravelTypeResultDtoMock = (overrideResponse: Partial<TravelTypeResultDto> = {}): TravelTypeResultDto => ({...{code: faker.helpers.arrayElement([faker.helpers.arrayElement(['adventurer','explorer','relaxer','foodie'] as const), undefined]), title: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), emoji: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), description: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), tags: faker.helpers.arrayElement([Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => (faker.string.alpha({length: {min: 10, max: 20}}))), undefined])}, ...overrideResponse});

export const getSubmitResponseMock = (overrideResponse: Partial<Extract<ApiResponseTravelTypeResultDto, object>> = {}): ApiResponseTravelTypeResultDto => ({success: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]), message: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), undefined]), data: faker.helpers.arrayElement([faker.helpers.arrayElement([{...getSubmitResponseTravelTypeResultDtoMock()},null,]), undefined]), ...overrideResponse})

export const getGetQuizResponseQuizDtoMock = (overrideResponse: Partial<QuizDto> = {}): QuizDto => ({...{questions: faker.helpers.arrayElement([Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => ({id: faker.helpers.arrayElement([faker.number.int(), undefined]), text: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), options: faker.helpers.arrayElement([Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => ({id: faker.helpers.arrayElement([faker.number.int(), undefined]), text: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined])})), undefined])})), undefined])}, ...overrideResponse});

export const getGetQuizResponseMock = (overrideResponse: Partial<Extract<ApiResponseQuizDto, object>> = {}): ApiResponseQuizDto => ({success: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]), message: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), undefined]), data: faker.helpers.arrayElement([faker.helpers.arrayElement([{...getGetQuizResponseQuizDtoMock()},null,]), undefined]), ...overrideResponse})


export const getSubmitMockHandler = (overrideResponse?: ApiResponseTravelTypeResultDto | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<ApiResponseTravelTypeResultDto> | ApiResponseTravelTypeResultDto), options?: RequestHandlerOptions) => {
  return http.post('*/travel-types/submit', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getSubmitResponseMock(),
      { status: 200
      })
  }, options)
}

export const getGetQuizMockHandler = (overrideResponse?: ApiResponseQuizDto | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<ApiResponseQuizDto> | ApiResponseQuizDto), options?: RequestHandlerOptions) => {
  return http.get('*/travel-types/quiz', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetQuizResponseMock(),
      { status: 200
      })
  }, options)
}
export const getTravelTypeMock = () => [
  getSubmitMockHandler(),
  getGetQuizMockHandler()
]
