/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useInfiniteQuery,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ApiResponseDestinationDetailDto,
  ApiResponseDestinationPageDto,
  ApiResponseListDestinationDto,
  GetList1Params,
  GetRandomParams
} from '../schemas';

import { orvalMutator } from '../../../services/api/orval-mutator';




/**
 * category(attraction/festival/experience)는 필수, region(충북 11개 시군)은 선택 — 생략하면 충북 전체를 대상으로 조회한다.
 *
 * **검증된 매핑 정보 (추측 아님, TourAPI 실호출로 확인)**
 * - sigunguCode: 1 괴산 · 2 단양 · 3 보은 · 4 영동 · 5 옥천 · 6 음성 · 7 제천 · 8 진천 · 9 청원(2014년 청주시 통합으로 폐지, 미사용) · 10 청주 · 11 충주 · 12 증평
 * - cat2=A0203(체험관광지): areaBasedList2가 cat2 필터를 서버 사이드에서 직접 지원함을 확인
 * - 결과 0건이면 TourAPI가 items를 객체가 아닌 빈 문자열("")로 내려주는 특이 케이스가 있어 방어적으로 파싱함
 *
 * **알아두어야 할 설계 트레이드오프**
 * 1. 목록에는 간단설명(description)이 없다 — TourAPI 목록 API(areaBasedList2)엔 원래 없는 필드라 넣으려면 항목마다 상세공통조회(detailCommon2)를 추가 호출해야 했는데(N+1), 응답 지연과 일일 호출한도 소진 문제로 2026-07-04 팀 논의 후 제외했다. 설명이 필요하면 상세 조회(GET /destinations/{id})를 이용한다.
 * 2. attraction 탭과 experience 탭은 TourAPI 분류상 일부 겹친다(체험관광지도 관광지 탭에 함께 나옴). 겹침 없이 분리하려면 TourAPI가 계산해주는 totalCount 기반 페이지네이션과 어긋나서, 정확한 페이지네이션을 우선하고 겹침은 허용했다.
 * @summary 관광지/축제/체험관광 목록 조회
 */
export const getList1 = (
    params: GetList1Params,
 signal?: AbortSignal
) => {


      return orvalMutator<ApiResponseDestinationPageDto>(
      {url: `/destinations`, method: 'GET',
        params, signal
    },
      );
    }




export const getGetList1InfiniteQueryKey = (params?: GetList1Params,) => {
    return [
    'infinite', `/destinations`, ...(params ? [params] : [])
    ] as const;
    }

export const getGetList1QueryKey = (params?: GetList1Params,) => {
    return [
    `/destinations`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetList1InfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getList1>>>, TError = unknown>(params: GetList1Params, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getList1>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetList1InfiniteQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getList1>>> = ({ signal }) => getList1(params, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getList1>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetList1InfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getList1>>>
export type GetList1InfiniteQueryError = unknown


export function useGetList1Infinite<TData = InfiniteData<Awaited<ReturnType<typeof getList1>>>, TError = unknown>(
 params: GetList1Params, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getList1>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getList1>>,
          TError,
          Awaited<ReturnType<typeof getList1>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetList1Infinite<TData = InfiniteData<Awaited<ReturnType<typeof getList1>>>, TError = unknown>(
 params: GetList1Params, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getList1>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getList1>>,
          TError,
          Awaited<ReturnType<typeof getList1>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetList1Infinite<TData = InfiniteData<Awaited<ReturnType<typeof getList1>>>, TError = unknown>(
 params: GetList1Params, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getList1>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 관광지/축제/체험관광 목록 조회
 */

export function useGetList1Infinite<TData = InfiniteData<Awaited<ReturnType<typeof getList1>>>, TError = unknown>(
 params: GetList1Params, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getList1>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetList1InfiniteQueryOptions(params,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getGetList1QueryOptions = <TData = Awaited<ReturnType<typeof getList1>>, TError = unknown>(params: GetList1Params, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getList1>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetList1QueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getList1>>> = ({ signal }) => getList1(params, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getList1>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetList1QueryResult = NonNullable<Awaited<ReturnType<typeof getList1>>>
export type GetList1QueryError = unknown


export function useGetList1<TData = Awaited<ReturnType<typeof getList1>>, TError = unknown>(
 params: GetList1Params, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getList1>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getList1>>,
          TError,
          Awaited<ReturnType<typeof getList1>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetList1<TData = Awaited<ReturnType<typeof getList1>>, TError = unknown>(
 params: GetList1Params, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getList1>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getList1>>,
          TError,
          Awaited<ReturnType<typeof getList1>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetList1<TData = Awaited<ReturnType<typeof getList1>>, TError = unknown>(
 params: GetList1Params, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getList1>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 관광지/축제/체험관광 목록 조회
 */

export function useGetList1<TData = Awaited<ReturnType<typeof getList1>>, TError = unknown>(
 params: GetList1Params, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getList1>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetList1QueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * 주소/유형/입장료/설명/태그/사진을 반환한다.
 *
 * - 입장료(admissionFee): TourAPI가 축제(usetimefestival 필드)에만 제공하는 정보라 관광지·체험관광은 필드 자체가 없어 항상 null.
 * - 유형(type): TourAPI cat2 코드(A0201=역사관광지, A0203=체험관광지 등)를 한글 라벨로 변환한 값.
 * - 태그(tags): TourAPI가 직접 주는 값이 아니라, 카테고리(#명소/#축제/#체험) · 고정값(#충북여행) · cat1/cat2 한글 라벨(#인문관광, #역사관광지 등) · 계절(있으면 #봄추천 등)을 조합해 서버가 만든다. 계절 무관 항목(역사관광지, 문화시설 등)은 계절 태그가 붙지 않는다.
 * - 사진(images): 대표사진(imageUrl) 1장 외에 갤러리 API(detailImage2)를 추가 호출해서 최대 3장까지 반환한다. 갤러리 사진이 없는 destination은 imageUrl 하나만 담겨 온다.
 * @summary 관광지/축제/체험관광 상세 조회
 */
export const getDetail = (
    id: number,
 signal?: AbortSignal
) => {


      return orvalMutator<ApiResponseDestinationDetailDto>(
      {url: `/destinations/${id}`, method: 'GET', signal
    },
      );
    }




export const getGetDetailInfiniteQueryKey = (id: number,) => {
    return [
    'infinite', `/destinations/${id}`
    ] as const;
    }

export const getGetDetailQueryKey = (id: number,) => {
    return [
    `/destinations/${id}`
    ] as const;
    }


export const getGetDetailInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getDetail>>>, TError = unknown>(id: number, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getDetail>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetDetailInfiniteQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getDetail>>> = ({ signal }) => getDetail(id, signal);





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getDetail>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetDetailInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getDetail>>>
export type GetDetailInfiniteQueryError = unknown


export function useGetDetailInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getDetail>>>, TError = unknown>(
 id: number, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getDetail>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDetail>>,
          TError,
          Awaited<ReturnType<typeof getDetail>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDetailInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getDetail>>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getDetail>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDetail>>,
          TError,
          Awaited<ReturnType<typeof getDetail>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDetailInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getDetail>>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getDetail>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 관광지/축제/체험관광 상세 조회
 */

export function useGetDetailInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getDetail>>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getDetail>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetDetailInfiniteQueryOptions(id,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getGetDetailQueryOptions = <TData = Awaited<ReturnType<typeof getDetail>>, TError = unknown>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDetail>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetDetailQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getDetail>>> = ({ signal }) => getDetail(id, signal);





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getDetail>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetDetailQueryResult = NonNullable<Awaited<ReturnType<typeof getDetail>>>
export type GetDetailQueryError = unknown


export function useGetDetail<TData = Awaited<ReturnType<typeof getDetail>>, TError = unknown>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDetail>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDetail>>,
          TError,
          Awaited<ReturnType<typeof getDetail>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDetail<TData = Awaited<ReturnType<typeof getDetail>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDetail>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDetail>>,
          TError,
          Awaited<ReturnType<typeof getDetail>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDetail<TData = Awaited<ReturnType<typeof getDetail>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDetail>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 관광지/축제/체험관광 상세 조회
 */

export function useGetDetail<TData = Awaited<ReturnType<typeof getDetail>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDetail>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetDetailQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * size(4/8/16/32 중 요청값 이하로 자동 스냅다운)만큼 무작위로 섞어서 뽑는다.
 *
 * - region을 지정하면 그 시군 안에서만 후보를 뽑는다. 생략하면 충북 전체가 대상.
 * - category(attraction/festival/experience)를 지정하면 그 카테고리만 대상으로 한다. 생략하면 기존과 동일하게 관광지+축제를 합친 풀에서 뽑는다.
 * - season(spring/summer/autumn/winter)을 지정하면 그 계절에 어울리는 항목만 대상으로 한다. 판정 방식: 축제는 실제 일정(eventstartdate) 월(月) 기준, 관광지/체험관광은 TourAPI 소분류(cat3) 중 계절색이 뚜렷한 코드만 매핑(해수욕장/계곡/폭포→여름, 온천→겨울 등). 나머지 대부분(역사관광지, 문화시설 등)은 계절 무관으로 보고, 요청한 계절과 정확히 일치하는 항목을 먼저 채운 뒤 모자란 자리만 계절 무관 항목으로 채운다. 봄/가을은 TourAPI 소분류상 계절 특화 코드 자체가 없어 대부분 계절 무관 항목으로 채워진다.
 * - 필터링 후 후보가 4개 미만이면 409 TOURNAMENT_POOL_TOO_SMALL
 * @summary 토너먼트용 랜덤 관광지 뽑기
 */
export const getRandom = (
    params?: GetRandomParams,
 signal?: AbortSignal
) => {


      return orvalMutator<ApiResponseListDestinationDto>(
      {url: `/destinations/random`, method: 'GET',
        params, signal
    },
      );
    }




export const getGetRandomInfiniteQueryKey = (params?: GetRandomParams,) => {
    return [
    'infinite', `/destinations/random`, ...(params ? [params] : [])
    ] as const;
    }

export const getGetRandomQueryKey = (params?: GetRandomParams,) => {
    return [
    `/destinations/random`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetRandomInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getRandom>>>, TError = unknown>(params?: GetRandomParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getRandom>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetRandomInfiniteQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getRandom>>> = ({ signal }) => getRandom(params, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getRandom>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetRandomInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getRandom>>>
export type GetRandomInfiniteQueryError = unknown


export function useGetRandomInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getRandom>>>, TError = unknown>(
 params: undefined |  GetRandomParams, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getRandom>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRandom>>,
          TError,
          Awaited<ReturnType<typeof getRandom>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetRandomInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getRandom>>>, TError = unknown>(
 params?: GetRandomParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getRandom>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRandom>>,
          TError,
          Awaited<ReturnType<typeof getRandom>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetRandomInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getRandom>>>, TError = unknown>(
 params?: GetRandomParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getRandom>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 토너먼트용 랜덤 관광지 뽑기
 */

export function useGetRandomInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getRandom>>>, TError = unknown>(
 params?: GetRandomParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getRandom>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetRandomInfiniteQueryOptions(params,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getGetRandomQueryOptions = <TData = Awaited<ReturnType<typeof getRandom>>, TError = unknown>(params?: GetRandomParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRandom>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetRandomQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getRandom>>> = ({ signal }) => getRandom(params, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getRandom>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetRandomQueryResult = NonNullable<Awaited<ReturnType<typeof getRandom>>>
export type GetRandomQueryError = unknown


export function useGetRandom<TData = Awaited<ReturnType<typeof getRandom>>, TError = unknown>(
 params: undefined |  GetRandomParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRandom>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRandom>>,
          TError,
          Awaited<ReturnType<typeof getRandom>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetRandom<TData = Awaited<ReturnType<typeof getRandom>>, TError = unknown>(
 params?: GetRandomParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRandom>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRandom>>,
          TError,
          Awaited<ReturnType<typeof getRandom>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetRandom<TData = Awaited<ReturnType<typeof getRandom>>, TError = unknown>(
 params?: GetRandomParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRandom>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 토너먼트용 랜덤 관광지 뽑기
 */

export function useGetRandom<TData = Awaited<ReturnType<typeof getRandom>>, TError = unknown>(
 params?: GetRandomParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRandom>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetRandomQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






