/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Tripbite api
 * OpenAPI spec version: v1.0.0
 */
import {
  useInfiniteQuery,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ApiResponseSettingsDto,
  UpdateNotificationSettingsDto
} from '../schemas';

import { orvalMutator } from '../../../services/api/orval-mutator';




/**
 * 요청 바디에 없는(null) 필드는 기존 값을 그대로 유지한다.
 * @summary 알림 설정 부분 수정
 */
export const updateNotificationSettings = (
    updateNotificationSettingsDto: UpdateNotificationSettingsDto,
 signal?: AbortSignal
) => {


      return orvalMutator<ApiResponseSettingsDto>(
      {url: `/settings/notifications`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateNotificationSettingsDto, signal
    },
      );
    }




export const getUpdateNotificationSettingsQueryKey = (updateNotificationSettingsDto?: UpdateNotificationSettingsDto,) => {
    return [
    'PATCH', `/settings/notifications`, updateNotificationSettingsDto
    ] as const;
    }


export const getUpdateNotificationSettingsQueryOptions = <TData = Awaited<ReturnType<typeof updateNotificationSettings>>, TError = unknown>(updateNotificationSettingsDto: UpdateNotificationSettingsDto, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof updateNotificationSettings>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getUpdateNotificationSettingsQueryKey(updateNotificationSettingsDto);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof updateNotificationSettings>>> = ({ signal }) => updateNotificationSettings(updateNotificationSettingsDto, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof updateNotificationSettings>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type UpdateNotificationSettingsQueryResult = NonNullable<Awaited<ReturnType<typeof updateNotificationSettings>>>
export type UpdateNotificationSettingsQueryError = unknown


export function useUpdateNotificationSettings<TData = Awaited<ReturnType<typeof updateNotificationSettings>>, TError = unknown>(
 updateNotificationSettingsDto: UpdateNotificationSettingsDto, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof updateNotificationSettings>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof updateNotificationSettings>>,
          TError,
          Awaited<ReturnType<typeof updateNotificationSettings>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUpdateNotificationSettings<TData = Awaited<ReturnType<typeof updateNotificationSettings>>, TError = unknown>(
 updateNotificationSettingsDto: UpdateNotificationSettingsDto, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof updateNotificationSettings>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof updateNotificationSettings>>,
          TError,
          Awaited<ReturnType<typeof updateNotificationSettings>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUpdateNotificationSettings<TData = Awaited<ReturnType<typeof updateNotificationSettings>>, TError = unknown>(
 updateNotificationSettingsDto: UpdateNotificationSettingsDto, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof updateNotificationSettings>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 알림 설정 부분 수정
 */

export function useUpdateNotificationSettings<TData = Awaited<ReturnType<typeof updateNotificationSettings>>, TError = unknown>(
 updateNotificationSettingsDto: UpdateNotificationSettingsDto, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof updateNotificationSettings>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getUpdateNotificationSettingsQueryOptions(updateNotificationSettingsDto,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * @summary 설정 조회
 */
export const getSettings = (

 signal?: AbortSignal
) => {


      return orvalMutator<ApiResponseSettingsDto>(
      {url: `/settings`, method: 'GET', signal
    },
      );
    }




export const getGetSettingsInfiniteQueryKey = () => {
    return [
    'infinite', `/settings`
    ] as const;
    }

export const getGetSettingsQueryKey = () => {
    return [
    `/settings`
    ] as const;
    }


export const getGetSettingsInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getSettings>>>, TError = unknown>( options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getSettings>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetSettingsInfiniteQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getSettings>>> = ({ signal }) => getSettings(signal);





   return  { queryKey, queryFn, ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getSettings>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetSettingsInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getSettings>>>
export type GetSettingsInfiniteQueryError = unknown


export function useGetSettingsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getSettings>>>, TError = unknown>(
  options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getSettings>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSettings>>,
          TError,
          Awaited<ReturnType<typeof getSettings>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSettingsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getSettings>>>, TError = unknown>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getSettings>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSettings>>,
          TError,
          Awaited<ReturnType<typeof getSettings>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSettingsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getSettings>>>, TError = unknown>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getSettings>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 설정 조회
 */

export function useGetSettingsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getSettings>>>, TError = unknown>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getSettings>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetSettingsInfiniteQueryOptions(options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getGetSettingsQueryOptions = <TData = Awaited<ReturnType<typeof getSettings>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSettings>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetSettingsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getSettings>>> = ({ signal }) => getSettings(signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getSettings>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetSettingsQueryResult = NonNullable<Awaited<ReturnType<typeof getSettings>>>
export type GetSettingsQueryError = unknown


export function useGetSettings<TData = Awaited<ReturnType<typeof getSettings>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSettings>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSettings>>,
          TError,
          Awaited<ReturnType<typeof getSettings>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSettings<TData = Awaited<ReturnType<typeof getSettings>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSettings>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSettings>>,
          TError,
          Awaited<ReturnType<typeof getSettings>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSettings<TData = Awaited<ReturnType<typeof getSettings>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSettings>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 설정 조회
 */

export function useGetSettings<TData = Awaited<ReturnType<typeof getSettings>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSettings>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetSettingsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






