/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Tripbite api
 * OpenAPI spec version: v1.0.0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  ApiResponseSettingsDto,
  SettingsDto
} from '../schemas';


export const getUpdateNotificationSettingsResponseSettingsDtoMock = (overrideResponse: Partial<SettingsDto> = {}): SettingsDto => ({...{notifications: faker.helpers.arrayElement([{pushEnabled: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]), inAppEnabled: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]), letterReceived: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]), letterLiked: faker.helpers.arrayElement([faker.datatype.boolean(), undefined])}, undefined])}, ...overrideResponse});

export const getUpdateNotificationSettingsResponseMock = (overrideResponse: Partial<Extract<ApiResponseSettingsDto, object>> = {}): ApiResponseSettingsDto => ({success: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]), message: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), undefined]), data: faker.helpers.arrayElement([faker.helpers.arrayElement([{...getUpdateNotificationSettingsResponseSettingsDtoMock()},null,]), undefined]), ...overrideResponse})

export const getGetSettingsResponseSettingsDtoMock = (overrideResponse: Partial<SettingsDto> = {}): SettingsDto => ({...{notifications: faker.helpers.arrayElement([{pushEnabled: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]), inAppEnabled: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]), letterReceived: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]), letterLiked: faker.helpers.arrayElement([faker.datatype.boolean(), undefined])}, undefined])}, ...overrideResponse});

export const getGetSettingsResponseMock = (overrideResponse: Partial<Extract<ApiResponseSettingsDto, object>> = {}): ApiResponseSettingsDto => ({success: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]), message: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), undefined]), data: faker.helpers.arrayElement([faker.helpers.arrayElement([{...getGetSettingsResponseSettingsDtoMock()},null,]), undefined]), ...overrideResponse})


export const getUpdateNotificationSettingsMockHandler = (overrideResponse?: ApiResponseSettingsDto | ((info: Parameters<Parameters<typeof http.patch>[1]>[0]) => Promise<ApiResponseSettingsDto> | ApiResponseSettingsDto), options?: RequestHandlerOptions) => {
  return http.patch('*/settings/notifications', async (info: Parameters<Parameters<typeof http.patch>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getUpdateNotificationSettingsResponseMock(),
      { status: 200
      })
  }, options)
}

export const getGetSettingsMockHandler = (overrideResponse?: ApiResponseSettingsDto | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<ApiResponseSettingsDto> | ApiResponseSettingsDto), options?: RequestHandlerOptions) => {
  return http.get('*/settings', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetSettingsResponseMock(),
      { status: 200
      })
  }, options)
}
export const getSettingsMock = () => [
  getUpdateNotificationSettingsMockHandler(),
  getGetSettingsMockHandler()
]
