/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Tripbite api
 * OpenAPI spec version: v1.0.0
 */
import {
  useInfiniteQuery,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ApiResponseLetterDto,
  ApiResponseLetterPageDto,
  ComposeLetterRequestDto,
  GetLikedParams,
  GetReceivedParams,
  GetSavedParams,
  GetSentParams
} from '../schemas';

import { orvalMutator } from '../../../services/api/orval-mutator';




/**
 * 본문은 정확히 5자여야 하고 서버단 금칙어 필터를 통과해야 한다. 작성 즉시 본인을 제외한 랜덤 유저 1명이 수신자로 정해지고, 랜덤 시간(1분~3시간) 뒤에 실제로 배송된다(즉시 발송 아님).
 * @summary 편지 작성
 */
export const compose = (
    composeLetterRequestDto: ComposeLetterRequestDto,
 signal?: AbortSignal
) => {


      return orvalMutator<ApiResponseLetterDto>(
      {url: `/letters`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: composeLetterRequestDto, signal
    },
      );
    }




export const getComposeQueryKey = (composeLetterRequestDto?: ComposeLetterRequestDto,) => {
    return [
    'POST', `/letters`, composeLetterRequestDto
    ] as const;
    }


export const getComposeQueryOptions = <TData = Awaited<ReturnType<typeof compose>>, TError = unknown>(composeLetterRequestDto: ComposeLetterRequestDto, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof compose>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getComposeQueryKey(composeLetterRequestDto);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof compose>>> = ({ signal }) => compose(composeLetterRequestDto, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof compose>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ComposeQueryResult = NonNullable<Awaited<ReturnType<typeof compose>>>
export type ComposeQueryError = unknown


export function useCompose<TData = Awaited<ReturnType<typeof compose>>, TError = unknown>(
 composeLetterRequestDto: ComposeLetterRequestDto, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof compose>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof compose>>,
          TError,
          Awaited<ReturnType<typeof compose>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCompose<TData = Awaited<ReturnType<typeof compose>>, TError = unknown>(
 composeLetterRequestDto: ComposeLetterRequestDto, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof compose>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof compose>>,
          TError,
          Awaited<ReturnType<typeof compose>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCompose<TData = Awaited<ReturnType<typeof compose>>, TError = unknown>(
 composeLetterRequestDto: ComposeLetterRequestDto, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof compose>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 편지 작성
 */

export function useCompose<TData = Awaited<ReturnType<typeof compose>>, TError = unknown>(
 composeLetterRequestDto: ComposeLetterRequestDto, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof compose>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getComposeQueryOptions(composeLetterRequestDto,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * 받은 사람만 가능. 이미 저장 상태면 취소된다(취소하면 3일 경과 시 목록에서 빠질 수 있음).
 * @summary 편지 저장 토글
 */
export const save1 = (
    id: number,
 signal?: AbortSignal
) => {


      return orvalMutator<ApiResponseLetterDto>(
      {url: `/letters/${id}/save`, method: 'POST', signal
    },
      );
    }




export const getSave1QueryKey = (id: number,) => {
    return [
    'POST', `/letters/${id}/save`
    ] as const;
    }


export const getSave1QueryOptions = <TData = Awaited<ReturnType<typeof save1>>, TError = unknown>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof save1>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSave1QueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof save1>>> = ({ signal }) => save1(id, signal);





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof save1>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type Save1QueryResult = NonNullable<Awaited<ReturnType<typeof save1>>>
export type Save1QueryError = unknown


export function useSave1<TData = Awaited<ReturnType<typeof save1>>, TError = unknown>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof save1>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof save1>>,
          TError,
          Awaited<ReturnType<typeof save1>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSave1<TData = Awaited<ReturnType<typeof save1>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof save1>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof save1>>,
          TError,
          Awaited<ReturnType<typeof save1>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSave1<TData = Awaited<ReturnType<typeof save1>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof save1>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 편지 저장 토글
 */

export function useSave1<TData = Awaited<ReturnType<typeof save1>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof save1>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSave1QueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * 받은 사람만 가능. 이미 좋아요 상태면 취소된다.
 * @summary 편지 좋아요 토글
 */
export const like = (
    id: number,
 signal?: AbortSignal
) => {


      return orvalMutator<ApiResponseLetterDto>(
      {url: `/letters/${id}/like`, method: 'POST', signal
    },
      );
    }




export const getLikeQueryKey = (id: number,) => {
    return [
    'POST', `/letters/${id}/like`
    ] as const;
    }


export const getLikeQueryOptions = <TData = Awaited<ReturnType<typeof like>>, TError = unknown>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof like>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getLikeQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof like>>> = ({ signal }) => like(id, signal);





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof like>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type LikeQueryResult = NonNullable<Awaited<ReturnType<typeof like>>>
export type LikeQueryError = unknown


export function useLike<TData = Awaited<ReturnType<typeof like>>, TError = unknown>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof like>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof like>>,
          TError,
          Awaited<ReturnType<typeof like>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useLike<TData = Awaited<ReturnType<typeof like>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof like>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof like>>,
          TError,
          Awaited<ReturnType<typeof like>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useLike<TData = Awaited<ReturnType<typeof like>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof like>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 편지 좋아요 토글
 */

export function useLike<TData = Awaited<ReturnType<typeof like>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof like>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getLikeQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * 보낸 사람 또는 받은 사람만 조회할 수 있다. 받은 사람이 조회하면 읽음 처리되고, 아직 배송 전인 편지를 받은 사람이 조회하려 하면 404 LETTER_NOT_DELIVERED.
 * @summary 편지 상세 조회
 */
export const getById = (
    id: number,
 signal?: AbortSignal
) => {


      return orvalMutator<ApiResponseLetterDto>(
      {url: `/letters/${id}`, method: 'GET', signal
    },
      );
    }




export const getGetByIdInfiniteQueryKey = (id: number,) => {
    return [
    'infinite', `/letters/${id}`
    ] as const;
    }

export const getGetByIdQueryKey = (id: number,) => {
    return [
    `/letters/${id}`
    ] as const;
    }


export const getGetByIdInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getById>>>, TError = unknown>(id: number, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getById>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetByIdInfiniteQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getById>>> = ({ signal }) => getById(id, signal);





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getById>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetByIdInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getById>>>
export type GetByIdInfiniteQueryError = unknown


export function useGetByIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getById>>>, TError = unknown>(
 id: number, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getById>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getById>>,
          TError,
          Awaited<ReturnType<typeof getById>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetByIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getById>>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getById>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getById>>,
          TError,
          Awaited<ReturnType<typeof getById>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetByIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getById>>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getById>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 편지 상세 조회
 */

export function useGetByIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getById>>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getById>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetByIdInfiniteQueryOptions(id,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getGetByIdQueryOptions = <TData = Awaited<ReturnType<typeof getById>>, TError = unknown>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getById>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetByIdQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getById>>> = ({ signal }) => getById(id, signal);





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getById>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getById>>>
export type GetByIdQueryError = unknown


export function useGetById<TData = Awaited<ReturnType<typeof getById>>, TError = unknown>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getById>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getById>>,
          TError,
          Awaited<ReturnType<typeof getById>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetById<TData = Awaited<ReturnType<typeof getById>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getById>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getById>>,
          TError,
          Awaited<ReturnType<typeof getById>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetById<TData = Awaited<ReturnType<typeof getById>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getById>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 편지 상세 조회
 */

export function useGetById<TData = Awaited<ReturnType<typeof getById>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getById>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetByIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * 받은 사람만 가능. 편지 한 통에 수신자가 한 명뿐이라 삭제되면 완전히 사라진다 (보낸 사람의 보낸편지함에서도 사라짐).
 * @summary 편지 삭제
 */
export const _delete = (
    id: number,
 signal?: AbortSignal
) => {


      return orvalMutator<void>(
      {url: `/letters/${id}`, method: 'DELETE', signal
    },
      );
    }




export const getDeleteQueryKey = (id: number,) => {
    return [
    'DELETE', `/letters/${id}`
    ] as const;
    }


export const getDeleteQueryOptions = <TData = Awaited<ReturnType<typeof _delete>>, TError = unknown>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof _delete>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDeleteQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof _delete>>> = ({ signal }) => _delete(id, signal);





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof _delete>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type _DeleteQueryResult = NonNullable<Awaited<ReturnType<typeof _delete>>>
export type _DeleteQueryError = unknown


export function useDelete<TData = Awaited<ReturnType<typeof _delete>>, TError = unknown>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof _delete>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof _delete>>,
          TError,
          Awaited<ReturnType<typeof _delete>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDelete<TData = Awaited<ReturnType<typeof _delete>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof _delete>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof _delete>>,
          TError,
          Awaited<ReturnType<typeof _delete>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDelete<TData = Awaited<ReturnType<typeof _delete>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof _delete>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 편지 삭제
 */

export function useDelete<TData = Awaited<ReturnType<typeof _delete>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof _delete>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getDeleteQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * 내가 쓴 편지를 배송 상태와 무관하게 최신순으로 반환한다.
 * @summary 보낸 편지함
 */
export const getSent = (
    params?: GetSentParams,
 signal?: AbortSignal
) => {


      return orvalMutator<ApiResponseLetterPageDto>(
      {url: `/letters/sent`, method: 'GET',
        params, signal
    },
      );
    }




export const getGetSentInfiniteQueryKey = (params?: GetSentParams,) => {
    return [
    'infinite', `/letters/sent`, ...(params ? [params] : [])
    ] as const;
    }

export const getGetSentQueryKey = (params?: GetSentParams,) => {
    return [
    `/letters/sent`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetSentInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getSent>>>, TError = unknown>(params?: GetSentParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getSent>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetSentInfiniteQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getSent>>> = ({ signal }) => getSent(params, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getSent>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetSentInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getSent>>>
export type GetSentInfiniteQueryError = unknown


export function useGetSentInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getSent>>>, TError = unknown>(
 params: undefined |  GetSentParams, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getSent>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSent>>,
          TError,
          Awaited<ReturnType<typeof getSent>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSentInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getSent>>>, TError = unknown>(
 params?: GetSentParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getSent>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSent>>,
          TError,
          Awaited<ReturnType<typeof getSent>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSentInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getSent>>>, TError = unknown>(
 params?: GetSentParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getSent>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 보낸 편지함
 */

export function useGetSentInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getSent>>>, TError = unknown>(
 params?: GetSentParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getSent>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetSentInfiniteQueryOptions(params,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getGetSentQueryOptions = <TData = Awaited<ReturnType<typeof getSent>>, TError = unknown>(params?: GetSentParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSent>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetSentQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getSent>>> = ({ signal }) => getSent(params, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getSent>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetSentQueryResult = NonNullable<Awaited<ReturnType<typeof getSent>>>
export type GetSentQueryError = unknown


export function useGetSent<TData = Awaited<ReturnType<typeof getSent>>, TError = unknown>(
 params: undefined |  GetSentParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSent>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSent>>,
          TError,
          Awaited<ReturnType<typeof getSent>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSent<TData = Awaited<ReturnType<typeof getSent>>, TError = unknown>(
 params?: GetSentParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSent>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSent>>,
          TError,
          Awaited<ReturnType<typeof getSent>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSent<TData = Awaited<ReturnType<typeof getSent>>, TError = unknown>(
 params?: GetSentParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSent>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 보낸 편지함
 */

export function useGetSent<TData = Awaited<ReturnType<typeof getSent>>, TError = unknown>(
 params?: GetSentParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSent>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetSentQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * 받은 편지 중 저장한 것만 반환한다 — 3일 경과와 무관하게 계속 남아있다.
 * @summary 저장한 편지함
 */
export const getSaved = (
    params?: GetSavedParams,
 signal?: AbortSignal
) => {


      return orvalMutator<ApiResponseLetterPageDto>(
      {url: `/letters/saved`, method: 'GET',
        params, signal
    },
      );
    }




export const getGetSavedInfiniteQueryKey = (params?: GetSavedParams,) => {
    return [
    'infinite', `/letters/saved`, ...(params ? [params] : [])
    ] as const;
    }

export const getGetSavedQueryKey = (params?: GetSavedParams,) => {
    return [
    `/letters/saved`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetSavedInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getSaved>>>, TError = unknown>(params?: GetSavedParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getSaved>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetSavedInfiniteQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getSaved>>> = ({ signal }) => getSaved(params, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getSaved>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetSavedInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getSaved>>>
export type GetSavedInfiniteQueryError = unknown


export function useGetSavedInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getSaved>>>, TError = unknown>(
 params: undefined |  GetSavedParams, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getSaved>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSaved>>,
          TError,
          Awaited<ReturnType<typeof getSaved>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSavedInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getSaved>>>, TError = unknown>(
 params?: GetSavedParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getSaved>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSaved>>,
          TError,
          Awaited<ReturnType<typeof getSaved>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSavedInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getSaved>>>, TError = unknown>(
 params?: GetSavedParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getSaved>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 저장한 편지함
 */

export function useGetSavedInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getSaved>>>, TError = unknown>(
 params?: GetSavedParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getSaved>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetSavedInfiniteQueryOptions(params,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getGetSavedQueryOptions = <TData = Awaited<ReturnType<typeof getSaved>>, TError = unknown>(params?: GetSavedParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSaved>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetSavedQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getSaved>>> = ({ signal }) => getSaved(params, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getSaved>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetSavedQueryResult = NonNullable<Awaited<ReturnType<typeof getSaved>>>
export type GetSavedQueryError = unknown


export function useGetSaved<TData = Awaited<ReturnType<typeof getSaved>>, TError = unknown>(
 params: undefined |  GetSavedParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSaved>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSaved>>,
          TError,
          Awaited<ReturnType<typeof getSaved>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSaved<TData = Awaited<ReturnType<typeof getSaved>>, TError = unknown>(
 params?: GetSavedParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSaved>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSaved>>,
          TError,
          Awaited<ReturnType<typeof getSaved>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSaved<TData = Awaited<ReturnType<typeof getSaved>>, TError = unknown>(
 params?: GetSavedParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSaved>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 저장한 편지함
 */

export function useGetSaved<TData = Awaited<ReturnType<typeof getSaved>>, TError = unknown>(
 params?: GetSavedParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSaved>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetSavedQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * 배송 완료된 편지 중 저장했거나 받은 지 3일 이내인 것만 최신순으로 반환한다 (저장 안 한 채 3일이 지나면 실제로 삭제되진 않지만 이 목록에는 더 이상 나타나지 않는다).
 * @summary 받은 편지함
 */
export const getReceived = (
    params?: GetReceivedParams,
 signal?: AbortSignal
) => {


      return orvalMutator<ApiResponseLetterPageDto>(
      {url: `/letters/received`, method: 'GET',
        params, signal
    },
      );
    }




export const getGetReceivedInfiniteQueryKey = (params?: GetReceivedParams,) => {
    return [
    'infinite', `/letters/received`, ...(params ? [params] : [])
    ] as const;
    }

export const getGetReceivedQueryKey = (params?: GetReceivedParams,) => {
    return [
    `/letters/received`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetReceivedInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getReceived>>>, TError = unknown>(params?: GetReceivedParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getReceived>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetReceivedInfiniteQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getReceived>>> = ({ signal }) => getReceived(params, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getReceived>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetReceivedInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getReceived>>>
export type GetReceivedInfiniteQueryError = unknown


export function useGetReceivedInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getReceived>>>, TError = unknown>(
 params: undefined |  GetReceivedParams, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getReceived>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getReceived>>,
          TError,
          Awaited<ReturnType<typeof getReceived>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetReceivedInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getReceived>>>, TError = unknown>(
 params?: GetReceivedParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getReceived>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getReceived>>,
          TError,
          Awaited<ReturnType<typeof getReceived>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetReceivedInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getReceived>>>, TError = unknown>(
 params?: GetReceivedParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getReceived>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 받은 편지함
 */

export function useGetReceivedInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getReceived>>>, TError = unknown>(
 params?: GetReceivedParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getReceived>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetReceivedInfiniteQueryOptions(params,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getGetReceivedQueryOptions = <TData = Awaited<ReturnType<typeof getReceived>>, TError = unknown>(params?: GetReceivedParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReceived>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetReceivedQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getReceived>>> = ({ signal }) => getReceived(params, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getReceived>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetReceivedQueryResult = NonNullable<Awaited<ReturnType<typeof getReceived>>>
export type GetReceivedQueryError = unknown


export function useGetReceived<TData = Awaited<ReturnType<typeof getReceived>>, TError = unknown>(
 params: undefined |  GetReceivedParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReceived>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getReceived>>,
          TError,
          Awaited<ReturnType<typeof getReceived>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetReceived<TData = Awaited<ReturnType<typeof getReceived>>, TError = unknown>(
 params?: GetReceivedParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReceived>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getReceived>>,
          TError,
          Awaited<ReturnType<typeof getReceived>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetReceived<TData = Awaited<ReturnType<typeof getReceived>>, TError = unknown>(
 params?: GetReceivedParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReceived>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 받은 편지함
 */

export function useGetReceived<TData = Awaited<ReturnType<typeof getReceived>>, TError = unknown>(
 params?: GetReceivedParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReceived>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetReceivedQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * 받은 편지 중 좋아요 표시한 것만 반환한다. 받은편지함과 동일하게 저장하지 않은 채 3일이 지나면 목록에서 빠진다.
 * @summary 좋아요한 편지함
 */
export const getLiked = (
    params?: GetLikedParams,
 signal?: AbortSignal
) => {


      return orvalMutator<ApiResponseLetterPageDto>(
      {url: `/letters/liked`, method: 'GET',
        params, signal
    },
      );
    }




export const getGetLikedInfiniteQueryKey = (params?: GetLikedParams,) => {
    return [
    'infinite', `/letters/liked`, ...(params ? [params] : [])
    ] as const;
    }

export const getGetLikedQueryKey = (params?: GetLikedParams,) => {
    return [
    `/letters/liked`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetLikedInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getLiked>>>, TError = unknown>(params?: GetLikedParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getLiked>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetLikedInfiniteQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getLiked>>> = ({ signal }) => getLiked(params, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getLiked>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetLikedInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getLiked>>>
export type GetLikedInfiniteQueryError = unknown


export function useGetLikedInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getLiked>>>, TError = unknown>(
 params: undefined |  GetLikedParams, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getLiked>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLiked>>,
          TError,
          Awaited<ReturnType<typeof getLiked>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetLikedInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getLiked>>>, TError = unknown>(
 params?: GetLikedParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getLiked>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLiked>>,
          TError,
          Awaited<ReturnType<typeof getLiked>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetLikedInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getLiked>>>, TError = unknown>(
 params?: GetLikedParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getLiked>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 좋아요한 편지함
 */

export function useGetLikedInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getLiked>>>, TError = unknown>(
 params?: GetLikedParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getLiked>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetLikedInfiniteQueryOptions(params,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getGetLikedQueryOptions = <TData = Awaited<ReturnType<typeof getLiked>>, TError = unknown>(params?: GetLikedParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLiked>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetLikedQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getLiked>>> = ({ signal }) => getLiked(params, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getLiked>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetLikedQueryResult = NonNullable<Awaited<ReturnType<typeof getLiked>>>
export type GetLikedQueryError = unknown


export function useGetLiked<TData = Awaited<ReturnType<typeof getLiked>>, TError = unknown>(
 params: undefined |  GetLikedParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLiked>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLiked>>,
          TError,
          Awaited<ReturnType<typeof getLiked>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetLiked<TData = Awaited<ReturnType<typeof getLiked>>, TError = unknown>(
 params?: GetLikedParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLiked>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLiked>>,
          TError,
          Awaited<ReturnType<typeof getLiked>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetLiked<TData = Awaited<ReturnType<typeof getLiked>>, TError = unknown>(
 params?: GetLikedParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLiked>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 좋아요한 편지함
 */

export function useGetLiked<TData = Awaited<ReturnType<typeof getLiked>>, TError = unknown>(
 params?: GetLikedParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLiked>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetLikedQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






